/*
Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// CE AllReduce local-reduction kernel dispatcher.
//
// ncclCeLocalReduceKernelVec<T, RedOp, U> and its generated (type, redop)
// instantiations live in one TU each, generated by
// src/device/ce_reduce/generate.py into gensrc/ce_reduce/. This file has no
// device kernels of its own -- it is pure host code that picks the right
// pre-instantiated launcher based on (datatype, op). Splitting the kernels
// out this way lets the build compile/codegen all 40 instantiations in
// parallel instead of paying for them in a single serialized device-link
// pass (two of the 40 -- int8_t/uint8_t Min/Max -- are individually large
// enough that they used to dominate the entire build's wall-clock time).
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <algorithm>

// MUST come before nccl.h/ce_coll.h's transitive include of device.h. device.h
// typedefs `hip_bfloat16` to `__hip_bfloat16` ONLY if neither
// _HIP_INCLUDE_HIP_AMD_DETAIL_HIP_BFLOAT16_H_ nor _HIP_BFLOAT16_H_ is already
// defined when it runs; otherwise it leaves `hip_bfloat16` as whatever
// <hip/hip_bfloat16.h> (included below, and transitively by
// ce_reduce_impl.h) already defined -- the real, non-typedef'd struct. Every
// generated gensrc/ce_reduce/*.cpp launcher TU includes ce_reduce_impl.h (and
// therefore <hip/hip_bfloat16.h>) BEFORE nccl.h, so `hip_bfloat16` resolves
// to that real struct there. Getting the same resolution in THIS TU is not
// cosmetic: the extern template declaration below has to name the exact
// mangled symbol the device-linker emitted for that other TU, and the two
// `hip_bfloat16` spellings mangle differently
// (_Z...I12hip_bfloat16... vs _Z...I14__hip_bfloat16...). Confirmed by a
// failed first attempt: candidate built and linked clean, then
// reduce_scatter_perf failed at dynamic-symbol-resolution time with
// "undefined symbol: ...I14__hip_bfloat16..." because this TU's include
// order (nccl.h before any hip_bfloat16 header) had locked in the typedef
// path instead.
#include <hip/hip_bfloat16.h>

#include "nccl.h"
#include "param.h"
#include "ce_coll.h"

// Brings in VecTrait<T> (including the per-type ::Threads launch width) and
// the ncclCeLocalReduceKernelVec<T, RedOp, U> template declaration/definition
// itself. This is the SAME generated header every gensrc/ce_reduce/*.cpp
// launcher TU includes (generate.py copies ce_reduce_impl.h.in verbatim into
// it), reachable here because src/CMakeLists.txt already puts
// ${HIPIFY_DIR}/gensrc on the rccl target's include path. Including it does
// NOT, by itself, instantiate or compile any device code in this TU -- see
// the "wide launch" block below for why that matters.
#include "ce_reduce/ce_reduce_impl.h"

RCCL_PARAM(CeReduceMaxBlocks, "CE_REDUCE_MAX_BLOCKS", NCCL_CE_REDUCE_DEFAULT_BLOCKS);

int ncclCeLocalReduceMaxBlocks() {
  return (int)std::clamp<int64_t>(rcclParamCeReduceMaxBlocks(), 1, NCCL_CE_REDUCE_MAX_BLOCKS);
}

// Every generated launcher takes ncclCeLaunchPersistentReduce's argument list
// minus (datatype, op), which is what this file resolves to a symbol name.
#define NCCL_CE_LAUNCH_PARAMS \
  const void *in, void *out, int nRanks, size_t baseChunkElems, size_t tailChunkElems, size_t chunksPerShard, \
    size_t slotChunkElems, uint32_t *signalBuffer, size_t totalSteps, uint32_t *d_barrierSync, hipStream_t stream, \
    int coopLaunch

#define NCCL_CE_LAUNCH_ARGS \
  in, out, nRanks, baseChunkElems, tailChunkElems, chunksPerShard, slotChunkElems, signalBuffer, totalSteps, \
    d_barrierSync, stream, coopLaunch

#define NCCL_CE_DECLARE_TYPE(Type) \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Sum(NCCL_CE_LAUNCH_PARAMS); \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Prod(NCCL_CE_LAUNCH_PARAMS); \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Min(NCCL_CE_LAUNCH_PARAMS); \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Max(NCCL_CE_LAUNCH_PARAMS); \
  extern int ncclCeLocalReduceBlocks_##Type(size_t)

NCCL_CE_DECLARE_TYPE(f32);
NCCL_CE_DECLARE_TYPE(f64);
NCCL_CE_DECLARE_TYPE(f16);
NCCL_CE_DECLARE_TYPE(bf16);
NCCL_CE_DECLARE_TYPE(i32);
NCCL_CE_DECLARE_TYPE(u32);
NCCL_CE_DECLARE_TYPE(i64);
NCCL_CE_DECLARE_TYPE(u64);
NCCL_CE_DECLARE_TYPE(i8);
NCCL_CE_DECLARE_TYPE(u8);

// Avg is intentionally limited to the BF16 gradient path used by Primus.
extern ncclResult_t ncclCeLocalReduceLaunch_bf16_Avg(NCCL_CE_LAUNCH_PARAMS);

#undef NCCL_CE_DECLARE_TYPE

// *********************************************************************************
// Wide-launch path: same kernel, same device code, more threads per block.
//
// src/include/ce_coll.h carries a comment (left by an earlier round) that
// ce_reduce_launcher.cpp.in's `const int threads = 256;` is a plain literal
// with no indirection -- that file is outside this task's editable set, so
// that literal genuinely cannot be repointed at VecTrait<T>::Threads. But
// ncclCeLocalReduceKernelVec<T,RedOp,U> (ce_reduce_impl.h.in) reads
// blockDim.x at runtime; it has no codegen dependency on how many threads a
// given *caller* launches it with, beyond the __launch_bounds__ upper bound.
// So a second host-side launcher, defined in this file (which IS editable),
// can legally request more threads/block for the exact same, already
// device-compiled kernel instantiation -- up to VecTrait<T>::Threads, which
// is exactly the bound ce_reduce_impl.h.in's kernel template now declares.
//
// `extern template` (not a fresh instantiation) tells the compiler this
// specific <T, RedOp, U> is defined elsewhere, so this --offload-host-only
// TU (src/CMakeLists.txt's ENABLE_DEVICE_LINKER block: "ce_coll.cc, the main
// target, has no __global__ call sites and stays --offload-host-only" --
// ce_reduce.cc is compiled the same way) emits only a host-side reference,
// never a second, deviceless copy of the kernel that could race the real one
// for the weak symbol. The linker resolves it to the one real definition in
// gensrc/ce_reduce/ce_reduce_bf16_Avg.cpp's fat object, which
// cmake/DeviceLinker.cmake compiles with full HIP support specifically so
// "each fat binary is self-contained."
//
// `blocks` deliberately still comes from ncclCeLocalReduceBlocksT<T>, whose
// internal formula is pinned at 256 (see that function's comment) -- for
// every production chunk size the pre-clamp value vastly exceeds
// ncclCeLocalReduceMaxBlocks() at either 256 or 1024, so the clamped grid
// size this path actually launches is identical to what the unmodified
// generated launcher would have reported.
//
// Scope for now: bf16 Avg only, the one (type, redop) this campaign's ruler
// exercises. NCCL_CE_WIDE_LAUNCH_IMPL is written so extending to the other
// seven non-int8/uint8 types (already confirmed zero-spill at 1024 in the
// per-instantiation resource sweep) is a mechanical, one-line-per-redop
// addition once this is measured correct and fast.
// *********************************************************************************
extern template __global__ void ncclCeLocalReduceKernelVec<hip_bfloat16, 4, VecTrait<hip_bfloat16>::GpuUnroll>(
    const hip_bfloat16* __restrict__ in, hip_bfloat16* __restrict__ out, int nRanks, size_t baseChunkElems,
    size_t tailChunkElems, size_t chunksPerShard, size_t slotChunkElems, volatile uint32_t* signalBuffer,
    size_t totalSteps, uint32_t* d_barrierSync, bool coopLaunch);

#define NCCL_CE_WIDE_LAUNCH_IMPL(Tag, Type, RedName, RedVal) \
  static ncclResult_t ncclCeLocalReduceLaunchWide_##Tag##_##RedName(NCCL_CE_LAUNCH_PARAMS) { \
    using T = Type; \
    constexpr int UnrollFactor = VecTrait<T>::GpuUnroll; \
    constexpr int threads = VecTrait<T>::Threads; \
    const int blocks = ncclCeLocalReduceBlocksT<T>(baseChunkElems); \
    const T* inT = static_cast<const T*>(in); \
    T* outT = static_cast<T*>(out); \
    bool useCoopLaunch = (coopLaunch != 0); \
    (void)hipGetLastError(); \
    hipError_t e; \
    if (useCoopLaunch) { \
      void* kernelArgs[] = { \
        &inT,          &outT,       &nRanks,        &baseChunkElems, &tailChunkElems, &chunksPerShard, &slotChunkElems, \
        &signalBuffer, &totalSteps, &d_barrierSync, &useCoopLaunch, \
      }; \
      e = hipLaunchCooperativeKernel(reinterpret_cast<const void*>(&ncclCeLocalReduceKernelVec<T, RedVal, UnrollFactor>), \
                                     dim3(blocks), dim3(threads), kernelArgs, 0, stream); \
    } else { \
      hipLaunchKernelGGL((ncclCeLocalReduceKernelVec<T, RedVal, UnrollFactor>), dim3(blocks), dim3(threads), 0, stream, \
                         inT, outT, nRanks, baseChunkElems, tailChunkElems, chunksPerShard, slotChunkElems, signalBuffer, \
                         totalSteps, d_barrierSync, useCoopLaunch); \
      e = hipGetLastError(); \
    } \
    if (e != hipSuccess) { \
      printf("[CE reduce] wide launch failed: %d (%s)\n", (int)e, hipGetErrorString(e)); \
      return ncclUnhandledCudaError; \
    } \
    return ncclSuccess; \
  }

NCCL_CE_WIDE_LAUNCH_IMPL(bf16, hip_bfloat16, Avg, 4)

#undef NCCL_CE_WIDE_LAUNCH_IMPL

// *********************************************************************************
// ncclCeLaunchPersistentReduce -- host launcher
// *********************************************************************************
ncclResult_t ncclCeLaunchPersistentReduce(const void* in, void* out, int nRanks, size_t baseChunkElems,
                                          size_t tailChunkElems, size_t chunksPerShard, size_t slotChunkElems,
                                          uint32_t* signalBuffer, size_t totalSteps, uint32_t* d_barrierSync,
                                          ncclDataType_t datatype, ncclRedOp_t op, hipStream_t stream, int coopLaunch) {
#define NCCL_CE_DISPATCH_REDOP(Type) \
  do { \
    switch (op) { \
    case ncclSum: \
      return ncclCeLocalReduceLaunch_##Type##_Sum(NCCL_CE_LAUNCH_ARGS); \
    case ncclProd: \
      return ncclCeLocalReduceLaunch_##Type##_Prod(NCCL_CE_LAUNCH_ARGS); \
    case ncclMin: \
      return ncclCeLocalReduceLaunch_##Type##_Min(NCCL_CE_LAUNCH_ARGS); \
    case ncclMax: \
      return ncclCeLocalReduceLaunch_##Type##_Max(NCCL_CE_LAUNCH_ARGS); \
    default: \
      return ncclInvalidArgument; \
    } \
  } while (0)

  switch (datatype) {
  case ncclFloat32:
    NCCL_CE_DISPATCH_REDOP(f32);
  case ncclFloat64:
    NCCL_CE_DISPATCH_REDOP(f64);
  case ncclFloat16:
    NCCL_CE_DISPATCH_REDOP(f16);
  case ncclBfloat16:
    if (op == ncclAvg) return ncclCeLocalReduceLaunchWide_bf16_Avg(NCCL_CE_LAUNCH_ARGS);
    NCCL_CE_DISPATCH_REDOP(bf16);
  case ncclInt32:
    NCCL_CE_DISPATCH_REDOP(i32);
  case ncclUint32:
    NCCL_CE_DISPATCH_REDOP(u32);
  case ncclInt64:
    NCCL_CE_DISPATCH_REDOP(i64);
  case ncclUint64:
    NCCL_CE_DISPATCH_REDOP(u64);
  case ncclInt8:
    NCCL_CE_DISPATCH_REDOP(i8);
  case ncclUint8:
    NCCL_CE_DISPATCH_REDOP(u8);
  // fp8 (e4m3/e5m2) not currently supported for CE AR.
  default:
    return ncclInvalidArgument;
  }

#undef NCCL_CE_DISPATCH_REDOP
}

// *********************************************************************************
// ncclCeLocalReduceBlocks -- reduce-kernel block count for host-side reporting
// (redop-independent; mirrors the geometry the launcher above actually uses).
// *********************************************************************************
int ncclCeLocalReduceBlocks(ncclDataType_t datatype, size_t chunkElems) {
  if (chunkElems == 0) return 0;
  switch (datatype) {
  case ncclFloat32:
    return ncclCeLocalReduceBlocks_f32(chunkElems);
  case ncclFloat64:
    return ncclCeLocalReduceBlocks_f64(chunkElems);
  case ncclFloat16:
    return ncclCeLocalReduceBlocks_f16(chunkElems);
  case ncclBfloat16:
    return ncclCeLocalReduceBlocks_bf16(chunkElems);
  case ncclInt32:
    return ncclCeLocalReduceBlocks_i32(chunkElems);
  case ncclUint32:
    return ncclCeLocalReduceBlocks_u32(chunkElems);
  case ncclInt64:
    return ncclCeLocalReduceBlocks_i64(chunkElems);
  case ncclUint64:
    return ncclCeLocalReduceBlocks_u64(chunkElems);
  case ncclInt8:
    return ncclCeLocalReduceBlocks_i8(chunkElems);
  case ncclUint8:
    return ncclCeLocalReduceBlocks_u8(chunkElems);
  // fp8 (e4m3/e5m2) not currently supported for CE AR.
  default:
    return 0;
  }
}
