/*
Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// CE AllReduce local-reduction kernel dispatcher.
//
// ncclCeLocalReduceKernelVec<T, RedOp, U> and its generated (type, redop)
// instantiations live in one TU each, generated by
// src/device/ce_reduce/generate.py into gensrc/ce_reduce/. This file has no
// device kernels of its own -- it is pure host code that picks the right
// pre-instantiated launcher based on (datatype, op). Splitting the kernels
// out this way lets the build compile/codegen all 40 instantiations in
// parallel instead of paying for them in a single serialized device-link
// pass (two of the 40 -- int8_t/uint8_t Min/Max -- are individually large
// enough that they used to dominate the entire build's wall-clock time).
#include <hip/hip_runtime.h>
#include <stdint.h>
#include <algorithm>

#include "nccl.h"
#include "param.h"
#include "ce_coll.h"

RCCL_PARAM(CeReduceMaxBlocks, "CE_REDUCE_MAX_BLOCKS", NCCL_CE_REDUCE_MAX_BLOCKS);

int ncclCeLocalReduceMaxBlocks() {
  return (int)std::clamp<int64_t>(rcclParamCeReduceMaxBlocks(), 1, NCCL_CE_REDUCE_MAX_BLOCKS);
}

// Every generated launcher takes ncclCeLaunchPersistentReduce's argument list
// minus (datatype, op), which is what this file resolves to a symbol name.
#define NCCL_CE_LAUNCH_PARAMS \
  const void *in, void *out, int nRanks, size_t baseChunkElems, size_t tailChunkElems, size_t chunksPerShard, \
    size_t slotChunkElems, uint32_t *signalBuffer, size_t totalSteps, uint32_t *d_barrierSync, hipStream_t stream, \
    int coopLaunch, int perChunk

#define NCCL_CE_LAUNCH_ARGS \
  in, out, nRanks, baseChunkElems, tailChunkElems, chunksPerShard, slotChunkElems, signalBuffer, totalSteps, \
    d_barrierSync, stream, coopLaunch, perChunk

#define NCCL_CE_DECLARE_TYPE(Type) \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Sum(NCCL_CE_LAUNCH_PARAMS); \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Prod(NCCL_CE_LAUNCH_PARAMS); \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Min(NCCL_CE_LAUNCH_PARAMS); \
  extern ncclResult_t ncclCeLocalReduceLaunch_##Type##_Max(NCCL_CE_LAUNCH_PARAMS); \
  extern int ncclCeLocalReduceBlocks_##Type(size_t)

NCCL_CE_DECLARE_TYPE(f32);
NCCL_CE_DECLARE_TYPE(f64);
NCCL_CE_DECLARE_TYPE(f16);
NCCL_CE_DECLARE_TYPE(bf16);
NCCL_CE_DECLARE_TYPE(i32);
NCCL_CE_DECLARE_TYPE(u32);
NCCL_CE_DECLARE_TYPE(i64);
NCCL_CE_DECLARE_TYPE(u64);
NCCL_CE_DECLARE_TYPE(i8);
NCCL_CE_DECLARE_TYPE(u8);

// Avg is intentionally limited to the BF16 gradient path used by Primus.
extern ncclResult_t ncclCeLocalReduceLaunch_bf16_Avg(NCCL_CE_LAUNCH_PARAMS);

#undef NCCL_CE_DECLARE_TYPE

// *********************************************************************************
// ncclCeLaunchPersistentReduce -- host launcher
// *********************************************************************************
ncclResult_t ncclCeLaunchPersistentReduce(const void* in, void* out, int nRanks, size_t baseChunkElems,
                                          size_t tailChunkElems, size_t chunksPerShard, size_t slotChunkElems,
                                          uint32_t* signalBuffer, size_t totalSteps, uint32_t* d_barrierSync,
                                          ncclDataType_t datatype, ncclRedOp_t op, hipStream_t stream, int coopLaunch,
                                          int perChunk) {
#define NCCL_CE_DISPATCH_REDOP(Type) \
  do { \
    switch (op) { \
    case ncclSum: \
      return ncclCeLocalReduceLaunch_##Type##_Sum(NCCL_CE_LAUNCH_ARGS); \
    case ncclProd: \
      return ncclCeLocalReduceLaunch_##Type##_Prod(NCCL_CE_LAUNCH_ARGS); \
    case ncclMin: \
      return ncclCeLocalReduceLaunch_##Type##_Min(NCCL_CE_LAUNCH_ARGS); \
    case ncclMax: \
      return ncclCeLocalReduceLaunch_##Type##_Max(NCCL_CE_LAUNCH_ARGS); \
    default: \
      return ncclInvalidArgument; \
    } \
  } while (0)

  switch (datatype) {
  case ncclFloat32:
    NCCL_CE_DISPATCH_REDOP(f32);
  case ncclFloat64:
    NCCL_CE_DISPATCH_REDOP(f64);
  case ncclFloat16:
    NCCL_CE_DISPATCH_REDOP(f16);
  case ncclBfloat16:
    if (op == ncclAvg) return ncclCeLocalReduceLaunch_bf16_Avg(NCCL_CE_LAUNCH_ARGS);
    NCCL_CE_DISPATCH_REDOP(bf16);
  case ncclInt32:
    NCCL_CE_DISPATCH_REDOP(i32);
  case ncclUint32:
    NCCL_CE_DISPATCH_REDOP(u32);
  case ncclInt64:
    NCCL_CE_DISPATCH_REDOP(i64);
  case ncclUint64:
    NCCL_CE_DISPATCH_REDOP(u64);
  case ncclInt8:
    NCCL_CE_DISPATCH_REDOP(i8);
  case ncclUint8:
    NCCL_CE_DISPATCH_REDOP(u8);
  // fp8 (e4m3/e5m2) not currently supported for CE AR.
  default:
    return ncclInvalidArgument;
  }

#undef NCCL_CE_DISPATCH_REDOP
}

// *********************************************************************************
// ncclCeLocalReduceBlocks -- reduce-kernel block count for host-side reporting
// (redop-independent; mirrors the geometry the launcher above actually uses).
// *********************************************************************************
int ncclCeLocalReduceBlocks(ncclDataType_t datatype, size_t chunkElems) {
  if (chunkElems == 0) return 0;
  switch (datatype) {
  case ncclFloat32:
    return ncclCeLocalReduceBlocks_f32(chunkElems);
  case ncclFloat64:
    return ncclCeLocalReduceBlocks_f64(chunkElems);
  case ncclFloat16:
    return ncclCeLocalReduceBlocks_f16(chunkElems);
  case ncclBfloat16:
    return ncclCeLocalReduceBlocks_bf16(chunkElems);
  case ncclInt32:
    return ncclCeLocalReduceBlocks_i32(chunkElems);
  case ncclUint32:
    return ncclCeLocalReduceBlocks_u32(chunkElems);
  case ncclInt64:
    return ncclCeLocalReduceBlocks_i64(chunkElems);
  case ncclUint64:
    return ncclCeLocalReduceBlocks_u64(chunkElems);
  case ncclInt8:
    return ncclCeLocalReduceBlocks_i8(chunkElems);
  case ncclUint8:
    return ncclCeLocalReduceBlocks_u8(chunkElems);
  // fp8 (e4m3/e5m2) not currently supported for CE AR.
  default:
    return 0;
  }
}
