#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc.
# SPDX-License-Identifier:  MIT
"""
Static instruction execution pipeline table generator for rocprofiler-compute.

Builds ``src/rocprof_compute_soc/analysis_configs/instruction_pipelines.yaml``,
which groups mnemonic prefixes under the execution pipeline that runs them. A
mnemonic is the first word of a disassembly line, so the line
``v_add_f32_e32 v0, v1, v2`` is matched by the ``v_add_f32`` prefix under VALU.

The mapping comes from the AMDGPU TableGen files of the LLVM commit TheRock
pins, so the table holds the mnemonics the installed disassembler prints.

Everything happens in a temporary directory that is removed on exit. LLVM is
needed to build the file, not to read it.

Usage (from the ``rocprofiler-compute`` project root):
    ./tools/instruction_pipeline_generator.py [--output PATH]
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from collections.abc import Iterable
from enum import Enum
from pathlib import Path
from typing import NamedTuple, Optional

import yaml

DEFAULT_OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "rocprof_compute_soc"
    / "analysis_configs"
    / "instruction_pipelines.yaml"
)

HEADER = """\
# Generated by tools/instruction_pipeline_generator.py. Do not edit by hand.
#
# pipelines: each execution pipeline, listing the mnemonic prefixes that run on
# it. A mnemonic is the first word of a disassembly line, so
#
#     v_add_f32_e32 v0, v1, v2
#
# is matched under VALU by whichever prefix of v_add_f32_e32 is listed. The
# longest matching prefix wins, so s_waitcnt resolves on s_wait, not on s_.
#
# arch_overrides: the prefixes that run on a different pipeline for one
# architecture, where the hardware differs from the compiler's model. They are
# applied over pipelines, by the same longest match.
#
# repo, commit: the llvm-project checkout the mnemonics were read from.
"""


class Pipeline(str, Enum):
    """The execution pipelines, declared in the order rules are tried.

    An instruction can match more than one rule, and the first match wins.
    SCALAR and VALU come last because nearly every instruction matches one of
    them. Members are strings, so they land in the YAML as written.
    """

    MATRIX = "MATRIX"
    BRANCH = "BRANCH"
    BARRIER = "BARRIER"
    EXP = "EXP"
    INTERNAL = "INTERNAL"
    LDS = "LDS"
    VMEM = "VMEM"
    FLAT = "FLAT"
    SCALAR = "SCALAR"
    VALU = "VALU"


class InstructionRecord(NamedTuple):
    """One TableGen instruction record, reduced to what classification needs.

    ``pseudo`` identifies the instruction. Every encoding and per-family variant
    of one instruction carries the same value, which is what lets their
    encodings and their printed names be brought back together.
    """

    record_name: str
    pseudo: str
    mnemonics: frozenset[str]
    encodings: frozenset[str]


class Instruction(NamedTuple):
    """One instruction: every name it prints, and every encoding it sets."""

    mnemonics: frozenset[str]
    encodings: frozenset[str]


# Global and scratch memory runs on the flat pipe on gfx9.
FLAT_MEMORY = {"global_": Pipeline.FLAT, "scratch_": Pipeline.FLAT}

# On gfx942 and gfx950 the higher precision MFMA run on the vector ALU rather
# than the matrix pipe. f32 sources are named since v_mfma_f32_ would claim the
# low precision ones too.
VALU_MFMA = dict.fromkeys(
    (
        "v_mfma_f64_",
        "v_mfma_f32_16x16x1f32",
        "v_mfma_f32_16x16x4_f32",
        "v_mfma_f32_16x16x4f32",
        "v_mfma_f32_32x32x1f32",
        "v_mfma_f32_32x32x2_f32",
        "v_mfma_f32_32x32x2f32",
        "v_mfma_f32_4x4x1f32",
    ),
    Pipeline.VALU,
)

# What each architecture runs elsewhere than its encoding implies, for where
# the compiler's execution model of the hardware is incomplete.
ARCH_OVERRIDES = {
    "gfx908": FLAT_MEMORY,
    "gfx90a": FLAT_MEMORY,
    "gfx940": FLAT_MEMORY,
    "gfx941": FLAT_MEMORY,
    "gfx942": {**FLAT_MEMORY, **VALU_MFMA},
    "gfx950": {**FLAT_MEMORY, **VALU_MFMA},
}


class TableGen:
    """Reads the AMDGPU instruction definitions out of LLVM."""

    therock_repo = "https://github.com/ROCm/TheRock"
    therock_llvm_submodule = "compiler/amd-llvm"
    llvm_repo = "https://github.com/ROCm/llvm-project"
    sparse_paths = ("llvm/lib/Target/AMDGPU", "llvm/include/llvm")

    mnemonic_pattern = re.compile(r"^[a-z][a-z0-9_]*")

    @staticmethod
    def fetch_sources(work_path: Path) -> tuple:
        """Check out the pinned AMDGPU TableGen files, returning path and commit.

        TheRock pins the compiler as a submodule, and ls-tree reads that pin
        straight out of the object store, so nothing is checked out for it. The
        LLVM checkout is sparse, but takes the whole ``llvm/include/llvm``
        tree: the TableGen includes chain, and listing the exact
        subdirectories breaks whenever LLVM adds one.
        """
        therock_path = work_path / "therock"
        therock_path.mkdir(parents=True)
        run_git(therock_path, "init", "--quiet")
        run_git(therock_path, "remote", "add", "origin", TableGen.therock_repo)
        print(f"Reading the compiler pin from {TableGen.therock_repo}")
        run_git(therock_path, "fetch", "--quiet", "--depth", "1", "origin", "main")
        listing = run_git(
            therock_path, "ls-tree", "FETCH_HEAD", TableGen.therock_llvm_submodule
        )
        commit = listing.split()[2]

        llvm_path = work_path / "llvm"
        llvm_path.mkdir(parents=True)
        run_git(llvm_path, "init", "--quiet")
        run_git(llvm_path, "remote", "add", "origin", TableGen.llvm_repo)
        run_git(llvm_path, "sparse-checkout", "init", "--cone")
        run_git(llvm_path, "sparse-checkout", "set", *TableGen.sparse_paths)
        print(f"Fetching {commit[:12]} of {TableGen.llvm_repo}")
        run_git(
            llvm_path,
            "fetch",
            "--quiet",
            "--depth",
            "1",
            "--filter=blob:none",
            "origin",
            commit,
        )
        run_git(llvm_path, "checkout", "--quiet", "FETCH_HEAD")
        return llvm_path / "llvm", commit

    @staticmethod
    def dump(tblgen: Path, llvm_path: Path, dump_path: Path) -> dict:
        """Dump every AMDGPU TableGen record as JSON and load it."""
        target_path = llvm_path / "lib" / "Target" / "AMDGPU"
        subprocess.run(
            [
                str(tblgen),
                "--dump-json",
                "-I",
                str(target_path),
                "-I",
                str(llvm_path / "include"),
                str(target_path / "AMDGPU.td"),
                "-o",
                str(dump_path),
            ],
            check=True,
        )
        with open(dump_path, encoding="utf-8") as dump_file:
            return json.load(dump_file)

    @staticmethod
    def records(dump: dict) -> list[InstructionRecord]:
        """Reduce a tblgen JSON dump to one InstructionRecord per instruction.

        A dump record reads ``{"Mnemonic": "v_add_f32", "VALU": 1, "VOP3": 1}``,
        with a field per property LLVM tracks. Only the printed names, the
        pseudo the record belongs to, and the encodings Rules classifies on are
        kept.
        """
        records: list[InstructionRecord] = []
        for record_name in dump.get("!instanceof", {}).get("Instruction", []):
            record = dump[record_name]
            mnemonics = TableGen.mnemonics_for_record(record)
            if not mnemonics:
                continue
            records.append(
                InstructionRecord(
                    record_name=record_name,
                    pseudo=TableGen.pseudo_of_record(record_name, record),
                    mnemonics=frozenset(mnemonics),
                    encodings=frozenset(
                        encoding
                        for encoding in Rules.encoding_to_pipeline
                        if record.get(encoding)
                    ),
                )
            )
        return records

    @staticmethod
    def instructions(records: Iterable[InstructionRecord]) -> list[Instruction]:
        """Fold the records of one instruction back into one instruction.

        A record holds either the printed name or the encodings, rarely both. A
        concrete per-family record prints the name and can leave an encoding
        unset that its pseudo sets, so classifying a record on its own gives one
        spelling of an instruction a different pipeline from another.
        """
        mnemonics: dict[str, set[str]] = {}
        encodings: dict[str, set[str]] = {}
        for record in records:
            mnemonics.setdefault(record.pseudo, set()).update(record.mnemonics)
            encodings.setdefault(record.pseudo, set()).update(record.encodings)
        return [
            Instruction(
                mnemonics=frozenset(mnemonics[pseudo]),
                encodings=frozenset(encodings[pseudo]),
            )
            for pseudo in mnemonics
        ]

    @staticmethod
    def pseudo_of_record(record_name: str, record: dict) -> str:
        """Return the identity of the instruction a record belongs to.

        ``PseudoInstr`` is an opaque string, spelled as a record name for some
        instructions and as a lowercase name for others. Only its sameness
        matters: every variant of one instruction carries the same value. A
        record without one is a pseudo itself, and stands for its own
        instruction.
        """
        pseudo = record.get("PseudoInstr")
        return pseudo if isinstance(pseudo, str) and pseudo else record_name

    @staticmethod
    def mnemonics_for_record(record: dict) -> set[str]:
        """Return every mnemonic the disassembler may print for one record.

        ``Mnemonic`` holds the name and ``AsmString`` the form after any
        per-family rename. ``PseudoInstr`` is not read: it identifies the
        instruction rather than naming it, and holds text that is never printed,
        such as ``buffer_atomic_add_addr64``.

        Printed encoding suffixes are not built either. They are appended to the
        name, so the prefix the table stores already covers them.
        """
        bases: set[str] = set()
        for field in ("Mnemonic", "AsmString"):
            base = TableGen.leading_mnemonic(record.get(field))
            if base is not None:
                bases.add(base)
        return bases

    @staticmethod
    def leading_mnemonic(value: object) -> Optional[str]:
        """Return the mnemonic a field starts with, dropping what follows it.

        Operands follow the mnemonic in several fields, sometimes with no
        separating space (``v_add_co_ci_u32$vdst``), and pseudo records carry
        placeholder text that is never printed.
        """
        if not isinstance(value, str):
            return None
        match = TableGen.mnemonic_pattern.match(value.strip().lower())
        return match.group(0) if match else None


class Rules:
    """Decides which pipeline runs an instruction."""

    # LLVM compiler encoding type -> execution pipeline. SCALAR covers scalar
    # ALU and scalar memory because the hardware serves both from one pipeline.
    encoding_to_pipeline = {
        "IsMAI": Pipeline.MATRIX,
        "IsWMMA": Pipeline.MATRIX,
        "IsSWMMAC": Pipeline.MATRIX,
        "isBranch": Pipeline.BRANCH,
        "EXP": Pipeline.EXP,
        "DS": Pipeline.LDS,
        "LDSDIR": Pipeline.LDS,
        "MUBUF": Pipeline.VMEM,
        "MTBUF": Pipeline.VMEM,
        "MIMG": Pipeline.VMEM,
        "FLAT": Pipeline.FLAT,
        "SMRD": Pipeline.SCALAR,
        "SALU": Pipeline.SCALAR,
        "VALU": Pipeline.VALU,
    }

    # Mnemonic prefixes, for the pipelines no encoding type can tell apart.
    mnemonic_prefixes = {
        Pipeline.BARRIER: ("s_barrier", "s_wakeup_barrier", "s_get_barrier_state"),
        Pipeline.EXP: ("s_sendmsg",),
        Pipeline.INTERNAL: (
            "s_wait",
            "s_soft_wait",
            "s_delay",
            "s_set",
            "s_sleep",
            "s_monitor_sleep",
            "s_ttrace",
            "s_clause",
            "s_inst_prefetch",
            "s_incperflevel",
            "s_decperflevel",
            "s_icache_inv",
            "s_denorm_mode",
            "s_round_mode",
            "s_singleuse_vdst",
            "s_endpgm",
            "s_code_end",
            "s_nop",
            "s_trap",
            "s_wakeup",
        ),
        Pipeline.VMEM: ("global_", "scratch_"),
        Pipeline.FLAT: ("flat_",),
    }

    @staticmethod
    def classify(mnemonic: str, encodings: Iterable[str]) -> Optional[Pipeline]:
        """Return the execution pipeline for a mnemonic and its merged encodings.

        Each pipeline in turn claims the instruction if either its encodings or
        its prefixes match, so the enum order is the only thing deciding who
        wins.

        Returns None when no rule matches, which leaves the type unset rather
        than guessing a pipeline.
        """
        encoding_set = set(encodings)
        for pipeline in Pipeline:
            by_encoding = any(
                Rules.encoding_to_pipeline.get(encoding) == pipeline
                for encoding in encoding_set
            )
            by_prefix = mnemonic.startswith(Rules.mnemonic_prefixes.get(pipeline, ()))
            if by_encoding or by_prefix:
                return pipeline
        return None

    @staticmethod
    def build_table(instructions: Iterable[Instruction]) -> dict[str, Pipeline]:
        """Classify every instruction, dropping the ones no rule claims.

        The encodings are the instruction's, so every name it prints is
        classified from the same set and no two spellings of it can disagree
        over an encoding. The prefix rules still read the name itself, since a
        per-family rename is what they exist to catch.
        """
        table: dict[str, Pipeline] = {}
        for instruction in instructions:
            for mnemonic in instruction.mnemonics:
                pipeline = Rules.classify(mnemonic, instruction.encodings)
                if pipeline is not None:
                    table[mnemonic] = pipeline
        return table

    @staticmethod
    def apply_overrides(table: dict[str, Pipeline], arch: str) -> dict[str, Pipeline]:
        """Return the table as one architecture runs it."""
        overrides = ARCH_OVERRIDES.get(arch, {})
        if not overrides:
            return dict(table)
        return {
            mnemonic: Prefixes.longest_match(overrides, mnemonic) or pipeline
            for mnemonic, pipeline in table.items()
        }


class Prefixes:
    """Turns the classified mnemonics into the prefixes that stand for them."""

    @staticmethod
    def longest_match(
        prefixes: dict[str, Pipeline], mnemonic: str
    ) -> Optional[Pipeline]:
        """Return the pipeline of the longest prefix the mnemonic starts with."""
        for length in range(len(mnemonic), 0, -1):
            pipeline = prefixes.get(mnemonic[:length])
            if pipeline is not None:
                return pipeline
        return None

    @staticmethod
    def compress(table: dict[str, Pipeline]) -> dict[str, Pipeline]:
        """Return the prefixes that reproduce the table, and nothing longer.

        Walking the mnemonics as a trie, a node becomes a prefix as soon as
        everything below it runs on one pipeline. A descendant that disagrees
        gets a prefix of its own, which is longer and therefore wins, so
        s_wakeup stays INTERNAL while s_wakeup_barrier stays BARRIER.

        A prefix stops at a whole name or at an underscore, never inside a word,
        so the file reads as global_ and v_mfma_f64_ rather than glo and
        v_mfma_f.
        """
        children: dict[str, set[str]] = {}
        pipelines_below: dict[str, set[Pipeline]] = {}
        for mnemonic, pipeline in table.items():
            for end in range(len(mnemonic) + 1):
                pipelines_below.setdefault(mnemonic[:end], set()).add(pipeline)
                if end < len(mnemonic):
                    children.setdefault(mnemonic[:end], set()).add(mnemonic[: end + 1])

        prefixes: dict[str, Pipeline] = {}

        def walk(node: str, inherited: Optional[Pipeline]) -> None:
            below = pipelines_below[node]
            if node and len(below) == 1 and (node.endswith("_") or node in table):
                pipeline = next(iter(below))
                if pipeline != inherited:
                    prefixes[node] = pipeline
                return
            if node in table and table[node] != inherited:
                prefixes[node] = table[node]
                inherited = table[node]
            for child in sorted(children.get(node, ())):
                walk(child, inherited)

        walk("", None)
        return prefixes

    @staticmethod
    def mismatches(
        prefixes: dict[str, Pipeline], table: dict[str, Pipeline]
    ) -> list[str]:
        """Return the mnemonics the prefixes answer differently."""
        return sorted(
            mnemonic
            for mnemonic, pipeline in table.items()
            if Prefixes.longest_match(prefixes, mnemonic) != pipeline
        )


class Corpus:
    """What the code objects of the local ROCm install actually contain."""

    code_object_suffixes = ("*.hsaco", "*.co")
    # A disassembly line is "<mnemonic> <operands>" possibly followed by an
    # encoding comment; the mnemonic is always the first token.
    disassembly_line_pattern = re.compile(r"^([a-z][a-z0-9_]*)\s")

    @staticmethod
    def collect(rocm_path: Path, objdump: Path) -> set[str]:
        """Disassemble a ROCm install to see what mnemonics real code emits."""
        mnemonics: set[str] = set()
        for suffix in Corpus.code_object_suffixes:
            for code_object in sorted(rocm_path.rglob(suffix)):
                disassembly = subprocess.run(
                    [str(objdump), "-d", str(code_object)],
                    capture_output=True,
                    text=True,
                    check=False,
                ).stdout
                mnemonics |= Corpus.parse_mnemonics(disassembly)
        print(f"Corpus holds {len(mnemonics)} distinct mnemonics")
        return mnemonics

    @staticmethod
    def parse_mnemonics(disassembly: str) -> set[str]:
        """Collect the mnemonics of an llvm-objdump disassembly listing.

        A listing line reads ``s_endpgm  // 00000000191C: BF810000``, so its
        mnemonic is the first word.
        """
        mnemonics: set[str] = set()
        for line in disassembly.splitlines():
            match = Corpus.disassembly_line_pattern.match(line.strip())
            if match:
                mnemonics.add(match.group(1))
        return mnemonics


class Table:
    """The generated file."""

    @staticmethod
    def group_by_pipeline(prefixes: dict[str, Pipeline]) -> dict[str, list[str]]:
        """Group prefixes under their pipeline, in the order rules are tried."""
        grouped = {}
        for pipeline in Pipeline:
            members = sorted(p for p, value in prefixes.items() if value == pipeline)
            if members:
                grouped[pipeline.value] = members
        return grouped

    @staticmethod
    def build_document(commit: str, prefixes: dict[str, Pipeline]) -> dict:
        """Lay the file out: what runs where, and what differs per architecture."""
        return {
            "repo": TableGen.llvm_repo,
            "commit": commit,
            "arch_overrides": {
                arch: Table.group_by_pipeline(overrides)
                for arch, overrides in sorted(ARCH_OVERRIDES.items())
            },
            "pipelines": Table.group_by_pipeline(prefixes),
        }

    @staticmethod
    def write(output_path: Path, commit: str, prefixes: dict[str, Pipeline]) -> None:
        """Write the generated document under the explanatory header."""
        with open(output_path, "w", encoding="utf-8") as output_file:
            output_file.write(HEADER)
            yaml.safe_dump(
                Table.build_document(commit, prefixes),
                output_file,
                sort_keys=False,
                default_flow_style=False,
            )


def run_git(repository_path: Path, *arguments: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repository_path), *arguments],
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Where to write the generated table.",
    )
    args = parser.parse_args()

    rocm_path = Path(os.getenv("ROCM_PATH", "/opt/rocm"))
    tblgen = rocm_path / "lib" / "llvm" / "bin" / "llvm-tblgen"
    objdump = rocm_path / "lib" / "llvm" / "bin" / "llvm-objdump"
    for binary in (tblgen, objdump):
        if not binary.is_file():
            print(f"error: {binary} not found; set ROCM_PATH", file=sys.stderr)
            return 1

    corpus_mnemonics = Corpus.collect(rocm_path, objdump)
    if not corpus_mnemonics:
        print(
            f"error: no code objects found under {rocm_path}; "
            "coverage cannot be checked",
            file=sys.stderr,
        )
        return 1

    with tempfile.TemporaryDirectory(prefix="instruction_pipelines_") as work_dir:
        work_path = Path(work_dir)
        llvm_path, commit = TableGen.fetch_sources(work_path)
        print(f"Running llvm-tblgen on the AMDGPU target of {commit[:12]}")
        dump = TableGen.dump(tblgen, llvm_path, work_path / "amdgpu.json")
        records = TableGen.records(dump)

    instructions = TableGen.instructions(records)
    table = Rules.build_table(instructions)
    print(
        f"Classified {len(table)} mnemonics from {len(instructions)} instructions "
        f"in {len(records)} records"
    )

    prefixes = Prefixes.compress(table)
    print(f"Compressed to {len(prefixes)} prefixes")

    # Coverage is asked of the prefixes rather than the mnemonics, since a
    # printed encoding suffix has no entry of its own: v_add_f32_e32 is matched
    # by the prefix that v_add_f32 compressed into.
    uncovered = sorted(
        mnemonic
        for mnemonic in corpus_mnemonics
        if Prefixes.longest_match(prefixes, mnemonic) is None
    )
    if uncovered:
        print(
            f"error: {len(uncovered)} corpus mnemonics no prefix matches: "
            f"{uncovered[:10]}",
            file=sys.stderr,
        )
        return 1

    # The prefixes replace the mnemonics, so they have to answer for every one
    # of them, on every architecture that overrides part of the table.
    for arch in [None, *sorted(ARCH_OVERRIDES)]:
        expected = table if arch is None else Rules.apply_overrides(table, arch)
        merged = prefixes if arch is None else {**prefixes, **ARCH_OVERRIDES[arch]}
        mismatched = Prefixes.mismatches(merged, expected)
        if mismatched:
            where = arch or "the default table"
            print(
                f"error: {len(mismatched)} mnemonics change pipeline on {where}: "
                f"{mismatched[:10]}",
                file=sys.stderr,
            )
            return 1

    Table.write(args.output, commit, prefixes)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
