# Copyright (c) Advanced Micro Devices, Inc.
# SPDX-License-Identifier:  MIT

import csv
from dataclasses import dataclass
from enum import Flag
from pathlib import Path
from typing import Any, Optional, SupportsFloat, Union

import numpy as np
import pandas as pd

from utils import schema
from utils.logger import console_debug, console_error, console_warning
from utils.metrics.evaluation_pipeline import eval_metric
from utils.mi_gpu_spec import mi_gpu_specs
from utils.specs import MachineSpecs
from utils.utils_common import _workload_base_dir

# Log-axis extent for ceiling math.
XMIN = 0.01
XMAX_DEFAULT = 1000.0

CACHE_LEVELS = ["ai_l0", "ai_l1", "ai_l2", "ai_hbm", "ai_lds"]


# Enum class representing support of VALU and Matrix Operations
class OpsSupport(Flag):
    VALU = 1  # Peak VALU Ops supported
    MATRIX = 2  # Matrix Ops supported


# SUPPORTED_DATATYPES table indicates which datatypes per gpu arch can be generated by
# the GPU benchmarking for roofline feature.
SUPPORTED_DATATYPES: dict[str, dict[str, OpsSupport]] = {
    "gfx90a": {
        "FP16": OpsSupport.VALU | OpsSupport.MATRIX,
        "BF16": OpsSupport.MATRIX,
        "FP32": OpsSupport.VALU | OpsSupport.MATRIX,
        "FP64": OpsSupport.VALU | OpsSupport.MATRIX,
        "I8": OpsSupport.VALU | OpsSupport.MATRIX,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6, F8
    "gfx940": {
        "FP8": OpsSupport.MATRIX,
        "FP16": OpsSupport.VALU | OpsSupport.MATRIX,
        "BF16": OpsSupport.MATRIX,
        "FP32": OpsSupport.VALU | OpsSupport.MATRIX,
        "FP64": OpsSupport.VALU | OpsSupport.MATRIX,
        "I8": OpsSupport.VALU | OpsSupport.MATRIX,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6
    "gfx941": {
        "FP8": OpsSupport.MATRIX,
        "FP16": OpsSupport.VALU | OpsSupport.MATRIX,
        "BF16": OpsSupport.MATRIX,
        "FP32": OpsSupport.VALU | OpsSupport.MATRIX,
        "FP64": OpsSupport.VALU | OpsSupport.MATRIX,
        "I8": OpsSupport.VALU | OpsSupport.MATRIX,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6
    "gfx942": {
        "FP8": OpsSupport.MATRIX,
        "FP16": OpsSupport.VALU | OpsSupport.MATRIX,
        "BF16": OpsSupport.MATRIX,
        "FP32": OpsSupport.VALU | OpsSupport.MATRIX,
        "FP64": OpsSupport.VALU | OpsSupport.MATRIX,
        "I8": OpsSupport.VALU | OpsSupport.MATRIX,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6
    "gfx950": {
        "FP4": OpsSupport.MATRIX,
        "FP6": OpsSupport.MATRIX,
        "FP8": OpsSupport.MATRIX,
        "MXFP8": OpsSupport.MATRIX,
        "FP16": OpsSupport.VALU | OpsSupport.MATRIX,
        "BF16": OpsSupport.MATRIX,
        "FP32": OpsSupport.VALU | OpsSupport.MATRIX,
        "FP64": OpsSupport.VALU | OpsSupport.MATRIX,
        "I8": OpsSupport.VALU | OpsSupport.MATRIX,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },
    # For gfx115x series, we are turning off WMMA benchmarking for all arithmetic
    # precisions since we do not receive the respective counters from underlying tools
    # for analysis.
    "gfx1150": {
        "FP16": OpsSupport.VALU,
        "BF16": OpsSupport.VALU,
        "FP32": OpsSupport.VALU,
        "FP64": OpsSupport.VALU,
        "I8": OpsSupport.VALU,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6, F8
    "gfx1151": {
        "FP16": OpsSupport.VALU,
        "BF16": OpsSupport.VALU,
        "FP32": OpsSupport.VALU,
        "FP64": OpsSupport.VALU,
        "I8": OpsSupport.VALU,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6, F8
    "gfx1152": {
        "FP16": OpsSupport.VALU,
        "BF16": OpsSupport.VALU,
        "FP32": OpsSupport.VALU,
        "FP64": OpsSupport.VALU,
        "I8": OpsSupport.VALU,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6, F8
    "gfx1153": {
        "FP16": OpsSupport.VALU,
        "BF16": OpsSupport.VALU,
        "FP32": OpsSupport.VALU,
        "FP64": OpsSupport.VALU,
        "I8": OpsSupport.VALU,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },  # Unsupported: F4, F6, F8
    "gfx1250": {
        "FP4": OpsSupport.MATRIX,
        "FP6": OpsSupport.MATRIX,
        "FP8": OpsSupport.MATRIX,
        "MXFP8": OpsSupport.MATRIX,
        "FP16": OpsSupport.VALU | OpsSupport.MATRIX,
        "BF16": OpsSupport.MATRIX,
        "FP32": OpsSupport.VALU | OpsSupport.MATRIX,
        "FP64": OpsSupport.VALU,
        "I8": OpsSupport.VALU | OpsSupport.MATRIX,
        "I32": OpsSupport.VALU,
        "I64": OpsSupport.VALU,
    },
}


# Metric labels of the "Roofline Plot Points" table, mapped to PlotPoints fields.
_METRIC_TO_AI_FIELD = {
    "AI L0": "ai_l0",
    "AI L1": "ai_l1",
    "AI L2": "ai_l2",
    "AI HBM": "ai_hbm",
    "AI LDS": "ai_lds",
}

# Table ids defined in <arch>/0400_roofline.yaml and 0000_top_stats.yaml.
_ROOFLINE_RATES_TABLE_ID = 401
_ROOFLINE_POINTS_TABLE_ID = 402
_KERNEL_TOP_TABLE_ID = 1


################################################
# Helper funcs
################################################
@dataclass
class PlotPoints:
    """Data structure for storing roofline plot points."""

    ai_l0: list[list[float]]
    ai_l1: list[list[float]]
    ai_l2: list[list[float]]
    ai_hbm: list[list[float]]
    ai_lds: list[list[float]]
    kernelNames: list[str]
    counts: list[Optional[float]]
    totalTime: list[Optional[float]]
    pctRuntime: list[Optional[float]]
    timeUnit: str

    @classmethod
    def empty(cls) -> "PlotPoints":
        """Create empty plot points structure."""
        return cls(
            ai_l0=[[], []],
            ai_l1=[[], []],
            ai_l2=[[], []],
            ai_hbm=[[], []],
            ai_lds=[[], []],
            kernelNames=[],
            counts=[],
            totalTime=[],
            pctRuntime=[],
            timeUnit="",
        )


@dataclass
class GraphPoints:
    """Data structure for storing roofline graph ceiling points."""

    hbm: list[Union[list[float], float, None]]
    l2: list[Union[list[float], float, None]]
    l1: list[Union[list[float], float, None]]
    l0: list[Union[list[float], float, None]]
    lds: list[Union[list[float], float, None]]
    valu: list[Union[list[float], float, None]]
    matrix_ops: list[Union[list[float], float, None]]

    @classmethod
    def empty(cls) -> "GraphPoints":
        """Create empty graph points structure."""
        return cls(
            hbm=[None, None, None],
            l2=[None, None, None],
            l1=[None, None, None],
            l0=[None, None, None],
            lds=[None, None, None],
            valu=[None, None, None],
            matrix_ops=[None, None, None],
        )


@dataclass
class RooflineCsvData:
    """Parsed roofline.csv device IDs and benchmark columns by row order."""

    device_ids: list[int]
    columns: dict[str, list[str]]


################################################
# Helper functions
################################################
def sanitize_ai_value(value: Union[SupportsFloat, str, None]) -> float:
    """Coerce a raw AI/performance cell to a finite number.

    Cells come from an evaluated metric table, so a missing counter can surface
    as a sentinel string ("", "N/A"), as None, or as inf/NaN. Nonnumeric and
    nonfinite values become 0; finite values retain their sign.
    """
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return 0
    return numeric if np.isfinite(numeric) else 0


def sanitize_mem_level(mem_level: Union[list[str], str], gpu_model: str) -> list[str]:
    """
    Ensure cache level requests through --mem-level roofline analysis option
    are supported on the architecture, and have been normalized.
    """
    # Make mem_level a list if not already one
    levels_raw = mem_level if isinstance(mem_level, list) else [mem_level]

    # Normalize user-facing "vL1D" to CSV column name "L1" before filtering
    levels_raw = [("L1" if m == "vL1D" else m) for m in levels_raw]

    model_memory_levels = mi_gpu_specs.get_memory_levels(gpu_model)

    # Remove any requested mem levels not supported in the profiled arch
    levels = [m for m in levels_raw if m in model_memory_levels]

    if levels_raw != ["ALL"] and levels != levels_raw:
        console_warning(
            f"Cache levels requested with --mem-level for {gpu_model} are not valid- "
            "unsupported cache levels will not be displayed."
        )

    # An empty list means the mem_level was originally ALL, or the user requested
    # unsupported levels and we should default back to complete list of all
    # memory levels for the arch (ALL).
    levels = model_memory_levels if levels == [] else levels

    # Skip MALL since we do not benchmark for this at this time
    levels = [m for m in levels if m != "MALL"]

    return levels


# -------------------------------------------------------------------------------------
#                           Plot BW at each cache level
# -------------------------------------------------------------------------------------
def calc_ceilings(
    roofline_parameters: dict[str, Any],
    dtype: str,
    benchmark_data: dict[str, list[str]],
    mspec: MachineSpecs,
    device_row_index: int,
) -> dict[str, list[Union[list[float], float, None]]]:
    """Given benchmarking data, calculate ceilings (or peak performance) for
    empirical roofline"""

    # TODO: This is where filtering by memory level will need to occur for standalone
    graph_points: dict[str, list[Union[list[float], float, None]]] = {
        "hbm": [],
        "l2": [],
        "l1": [],
        "l0": [],
        "lds": [],
        "valu": [],
        "matrix_ops": [],
    }

    cache_hierarchy = sanitize_mem_level(
        roofline_parameters["mem_level"], mspec.gpu_model
    )

    x1 = y1 = x2 = y2 = -1
    x1_matrix = y1_matrix = x2_matrix = y2_matrix = -1

    ops_flops = "Ops" if dtype.startswith("I") else "Flops"

    peak_ops = 0.0
    if OpsSupport.VALU in SUPPORTED_DATATYPES[mspec.gpu_arch][dtype]:
        try:
            peak_ops = sanitize_ai_value(
                benchmark_data[f"{dtype}{ops_flops}"][device_row_index]
            )
        except KeyError:
            console_warning(
                f"Missing benchmark data for {dtype}{ops_flops} in benchmark_results. "
                "Skipping peak operations calculation. This may indicate incomplete or "
                "corrupted benchmark data."
            )
            return GraphPoints.empty().__dict__
        if peak_ops <= 0:
            console_warning(
                f"Invalid peak operations ({peak_ops}) for {dtype}{ops_flops}. "
                "Unable to construct finite compute roof geometry."
            )
            return GraphPoints.empty().__dict__

    for cache_level in cache_hierarchy:
        # Plot BW line
        curr_bw = f"{cache_level}Bw"
        try:
            peak_bw = sanitize_ai_value(benchmark_data[curr_bw][device_row_index])
        except KeyError:
            console_warning(
                f"Missing benchmark data for {curr_bw} in benchmark_results. "
                f"Skipping {cache_level} cache level. This may indicate incomplete or "
                "corrupted benchmark data."
            )
            continue

        if peak_bw <= 0:
            console_debug(
                f"Invalid peak bandwidth ({peak_bw}) for {cache_level}. Skipping."
            )
            continue

        x1 = float(XMIN)
        y1 = sanitize_ai_value(float(XMIN) * peak_bw)
        if y1 <= 0:
            console_debug(
                f"Peak bandwidth geometry underflowed for {cache_level}. Skipping."
            )
            continue

        x1_matrix = float(XMIN)
        x2_matrix = 0.0
        y1_matrix = y2_matrix = 0.0

        if OpsSupport.VALU in SUPPORTED_DATATYPES[mspec.gpu_arch][dtype]:
            x2 = sanitize_ai_value(peak_ops / peak_bw)
            y2 = peak_ops  # noqa

            # Plot Matrix Ops lines (NOTE: Assuming MI200 soc)
            x1_matrix = x2
            y1_matrix = peak_ops

        peak_matrix = 0.0
        if OpsSupport.MATRIX in SUPPORTED_DATATYPES[mspec.gpu_arch][dtype]:
            if dtype.startswith(("I", "B")):
                target_precision = dtype
            elif dtype.startswith("MX"):
                target_precision = f"MXF{dtype[4:]}"
            else:
                target_precision = f"F{dtype[2:]}"

            try:
                matrix_key = (
                    f"{roofline_parameters['matrix_ops_type']}"
                    f"{target_precision}{ops_flops}"
                )
                peak_matrix = sanitize_ai_value(
                    benchmark_data[matrix_key][device_row_index]
                )
                if peak_matrix > 0:
                    x2_matrix = sanitize_ai_value(peak_matrix / peak_bw)
                    y2_matrix = peak_matrix
                else:
                    console_debug(
                        f"Invalid matrix peak ({peak_matrix}) for {matrix_key}. "
                        f"Skipping {roofline_parameters['matrix_ops_type']} "
                        f"calculations for {cache_level} cache level."
                    )
            except KeyError:
                console_warning(
                    f"Missing benchmark data for "
                    f"{roofline_parameters['matrix_ops_type']}"
                    f"{target_precision}{ops_flops} in benchmark_results. "
                    f"Skipping {roofline_parameters['matrix_ops_type']} "
                    f"calculations for {cache_level} cache level. "
                    "This may indicate incomplete or corrupted benchmark data."
                )

        if y1_matrix <= 0 and y2_matrix <= 0:
            console_debug(
                f"No valid compute peak for {dtype} at {cache_level}. "
                "Skipping bandwidth geometry."
            )
            continue

        # Check which peak is higher for formatting bandwidth lines
        if y2_matrix > y1_matrix:  # peak_matrix
            peak_x = x2_matrix
            peak_y = y2_matrix
        else:  # peakVALU
            peak_x = x1_matrix
            peak_y = y1_matrix

        if peak_x <= 0:
            peak_x = float(XMIN)

        cache_key = cache_level.lower()
        graph_points[cache_key].extend([[x1, peak_x], [y1, peak_y], peak_bw])

    # ----------------------------------------------------------------------------------
    #                                     Plot computing roof
    # ----------------------------------------------------------------------------------
    if OpsSupport.VALU in SUPPORTED_DATATYPES[mspec.gpu_arch][dtype] and x2 > 0:
        # Plot FMA roof
        x0 = min(x2, XMAX_DEFAULT) if x2 < XMAX_DEFAULT else XMAX_DEFAULT

        graph_points["valu"].extend([
            [x0, XMAX_DEFAULT],
            [peak_ops, peak_ops],
            peak_ops,
        ])

    # Plot Matrix Ops roof
    if (
        OpsSupport.MATRIX in SUPPORTED_DATATYPES[mspec.gpu_arch][dtype]
        and x2_matrix > 0
    ):
        x0_matrix = (
            min(x2_matrix, XMAX_DEFAULT) if x2_matrix < XMAX_DEFAULT else XMAX_DEFAULT
        )

        graph_points["matrix_ops"].extend([
            [x0_matrix, XMAX_DEFAULT],
            [peak_matrix, peak_matrix],
            peak_matrix,
        ])

    return graph_points


# -------------------------------------------------------------------------------------
#                              Overlay application performance
# -------------------------------------------------------------------------------------
def _extract_ai_metrics(calc_table: Optional[pd.DataFrame]) -> dict[str, float]:
    """Read per-level AI and performance from a kernel's evaluated plot points.

    Returns one entry per ``CACHE_LEVELS`` field plus ``performance``, defaulting
    to 0.0 for any row the table does not carry.
    """
    metrics = dict.fromkeys(CACHE_LEVELS, 0.0)
    metrics["performance"] = 0.0
    if calc_table is None:
        return metrics
    for _, row in calc_table.iterrows():
        metric = row.get("Metric", "")
        value = row.get("Value", 0)
        if metric in _METRIC_TO_AI_FIELD:
            metrics[_METRIC_TO_AI_FIELD[metric]] = sanitize_ai_value(value)
        elif metric == "Performance (GFLOPs)":
            metrics["performance"] = sanitize_ai_value(value)
    return metrics


def _resolve_kernel_ids(workload: schema.Workload) -> list[int]:
    """Kernel row ids to plot: an explicit int filter, else every top kernel.

    WebUI passes string kernel names as filters and pre-narrows pmc_df, so in
    that case every id is processed and the caller's filtering is relied upon.
    """
    if workload.filter_kernel_ids and all(
        isinstance(kernel_id, int) for kernel_id in workload.filter_kernel_ids
    ):
        return workload.filter_kernel_ids
    if _KERNEL_TOP_TABLE_ID not in workload.dfs:
        return []
    return workload.dfs[_KERNEL_TOP_TABLE_ID].index.tolist()


def _evaluate_kernel_tables(
    arch_config: schema.ArchConfig,
    workload: schema.Workload,
    kernel_pmc_df: pd.DataFrame,
) -> dict[int, pd.DataFrame]:
    """Evaluate the roofline arch-config tables (401/402) for one kernel."""
    kernel_dfs: dict[int, pd.DataFrame] = {}
    kernel_dfs_type: dict[int, str] = {}
    for table_id in (_ROOFLINE_RATES_TABLE_ID, _ROOFLINE_POINTS_TABLE_ID):
        if table_id in arch_config.dfs:
            kernel_dfs[table_id] = arch_config.dfs[table_id].copy()
            kernel_dfs_type[table_id] = arch_config.dfs_type[table_id]
    # eval_metric keys off kernel_dfs only.
    eval_metric(
        kernel_dfs,
        kernel_dfs_type,
        arch_config.dfs_expressions,
        workload.sys_info.iloc[0],
        workload.roofline_peaks,
        kernel_pmc_df,
        debug=False,
    )
    return kernel_dfs


def _stat_or_none(row: pd.Series, column: Optional[str]) -> Optional[float]:
    """Read a top-kernels stat as a float, or None when missing or NaN."""
    if column is None or column not in row.index:
        return None
    value = row[column]
    return float(value) if pd.notna(value) else None


def _append_kernel_point(
    plot_points: PlotPoints,
    metrics: dict[str, float],
    kernel_name: str,
    stat_row: pd.Series,
    sum_column: Optional[str],
) -> None:
    """Append one kernel's AI points plus its joined top-kernel stats."""
    for ai_field in CACHE_LEVELS:
        getattr(plot_points, ai_field)[0].append(metrics[ai_field])
        getattr(plot_points, ai_field)[1].append(metrics["performance"])
    plot_points.kernelNames.append(kernel_name)
    plot_points.counts.append(_stat_or_none(stat_row, "Count"))
    plot_points.totalTime.append(_stat_or_none(stat_row, sum_column))
    plot_points.pctRuntime.append(_stat_or_none(stat_row, "Percent"))


def calc_ai_analyze(
    workload: schema.Workload,
    pmc_df: pd.DataFrame,
    arch_config: schema.ArchConfig,
) -> dict[str, Union[list[list[float]], list[str]]]:
    """
    Calculate per-kernel metrics and AI points with Roofline yamls using eval_metric.

    Caller must apply filters (e.g. parser.apply_filters) and pass the resulting
    DataFrame as pmc_df. This function only computes AI data points.
    """
    console_debug("calc_ai_analyze", "Starting calc_ai analysis using Roofline yamls")
    plot_points = PlotPoints.empty()

    workload.roofline_metrics = {}

    # Aggregate-time column name encodes the time unit, e.g. "Sum(ns)".
    sum_column: Optional[str] = None
    top_df = workload.dfs.get(_KERNEL_TOP_TABLE_ID)
    if top_df is not None:
        sum_column = next(
            (
                column
                for column in top_df.columns
                if column.startswith("Sum(") and column.endswith(")")
            ),
            None,
        )
        if sum_column:
            plot_points.timeUnit = sum_column[len("Sum(") : -1]

    kernel_ids_to_process = _resolve_kernel_ids(workload)
    console_debug("roofline", f"Found {len(kernel_ids_to_process)} kernels to process")

    if not kernel_ids_to_process:
        console_warning("No kernels found to process for roofline")
        return plot_points.__dict__

    for kernel_id in kernel_ids_to_process:
        if top_df is None or kernel_id not in top_df.index:
            continue
        kernel_name = top_df.loc[kernel_id, "Kernel_Name"]

        console_debug("roofline", f"Processing kernel {kernel_id}: {kernel_name[:50]}")

        # filter PMC data for specific kernel
        kernel_pmc_df = pmc_df[pmc_df["Kernel_Name"] == kernel_name]

        if kernel_pmc_df.empty:
            console_debug("roofline", f"No PMC data for kernel {kernel_id}")
            continue

        kernel_dfs = _evaluate_kernel_tables(arch_config, workload, kernel_pmc_df)

        metrics = _extract_ai_metrics(kernel_dfs.get(_ROOFLINE_POINTS_TABLE_ID))
        performance = metrics["performance"]
        console_debug(
            "roofline",
            f"Kernel {kernel_id}: "
            + ", ".join(
                f"{ai_field}={metrics[ai_field]:.2f}" for ai_field in CACHE_LEVELS
            )
            + f", Performance={performance:.2e} GFLOP/s",
        )

        if performance > 0:
            _append_kernel_point(
                plot_points,
                metrics,
                kernel_name,
                top_df.loc[kernel_id],
                sum_column,
            )
            console_debug(
                "roofline",
                f"Added kernel {kernel_id}: {kernel_name[:50]} to plot points",
            )
        else:
            console_debug(
                "roofline",
                f"Skipping kernel {kernel_id}: {kernel_name[:50]}"
                f" - no performance data",
            )

        # store metrics for display
        workload.roofline_metrics[kernel_id] = {
            "name": kernel_name,
            "ai_table": kernel_dfs.get(_ROOFLINE_RATES_TABLE_ID, pd.DataFrame()),
            "calc_table": kernel_dfs.get(_ROOFLINE_POINTS_TABLE_ID, pd.DataFrame()),
        }

    console_debug("roofline", f"Generated {len(plot_points.kernelNames)} plot points")
    return plot_points.__dict__


def machine_ceilings(
    roofline_parameters: dict[str, Any],
    mspec: MachineSpecs,
) -> tuple[list[float], list[float]]:
    """Return positive bandwidth and compute ceilings for one device."""
    base_dir = _workload_base_dir(roofline_parameters.get("workload_dir"))
    if base_dir is None:
        console_warning(
            "roofline",
            "Unable to read machine ceilings: workload path is absent",
        )
        return [], []
    roofline_csv = Path(base_dir) / "roofline.csv"
    try:
        csv_data = _parse_roofline_csv(roofline_csv)
        row_index = _resolve_device_row_index(
            csv_data, roofline_parameters["device_id"]
        )
        bandwidths = _device_values(csv_data.columns, row_index, ("Bw",))
        peaks = _device_values(csv_data.columns, row_index, ("Flops", "Ops"))
        if not bandwidths:
            raise ValueError("no usable bandwidth ceilings in roofline.csv")
        if not peaks:
            raise ValueError("no usable compute ceilings in roofline.csv")
    except (
        OSError,
        csv.Error,
        KeyError,
        TypeError,
        ValueError,
        IndexError,
        OverflowError,
    ) as error:
        console_warning(
            "roofline",
            f"Unable to read machine ceilings from {roofline_csv}: {error}",
        )
        return [], []
    console_debug(
        "roofline",
        f"Loaded machine ceilings for {mspec.gpu_model}: "
        f"{len(bandwidths)} bandwidth, {len(peaks)} compute values",
    )
    return bandwidths, peaks


def construct_roof(
    roofline_parameters: dict[str, Any],
    dtype: str,
    mspec: MachineSpecs,
) -> dict[str, list[Union[list[float], float, None]]]:
    """Load benchmark results from disk and compute the empirical roofline."""
    base_dir = _workload_base_dir(roofline_parameters.get("workload_dir"))

    try:
        benchmark_results = Path(base_dir) / "roofline.csv"
        csv_data = _parse_roofline_csv(benchmark_results)
        device_row_index = _resolve_device_row_index(
            csv_data, roofline_parameters["device_id"]
        )
    except (
        OSError,
        csv.Error,
        KeyError,
        TypeError,
        ValueError,
        IndexError,
        OverflowError,
    ) as error:
        console_error(
            "roofline",
            f"Failed to read benchmark results from {base_dir}: {error}",
            exit=False,
        )
        return GraphPoints.empty().__dict__

    benchmark_data = csv_data.columns
    expected_columns = _expected_benchmark_columns(roofline_parameters, dtype, mspec)
    missing_columns = [col for col in expected_columns if col not in benchmark_data]
    if missing_columns:
        console_warning(
            f"Missing expected columns in roofline.csv for datatype {dtype}: "
            f"{', '.join(missing_columns)}. "
            "The roofline plot may be incomplete. Consider regenerating "
            "benchmark data or cleaning the directory and re-running the analysis."
        )

    return calc_ceilings(
        roofline_parameters,
        dtype,
        benchmark_data,
        mspec,
        device_row_index,
    )


def _parse_roofline_csv(benchmark_results: Path) -> RooflineCsvData:
    """Parse roofline.csv into device IDs and benchmark columns by row order."""
    device_ids: list[int] = []
    seen_device_ids: set[int] = set()
    columns: dict[str, list[str]] = {}
    headers: list[str] = []
    expected_width = 0

    with open(benchmark_results, newline="", encoding="utf-8") as csvfile:
        for row_number, row in enumerate(csv.reader(csvfile, delimiter=","), start=1):
            if row_number == 1:
                if not row or len(row) < 2:
                    raise ValueError(
                        f"roofline.csv row {row_number} is missing benchmark columns"
                    )
                headers = row[1:]
                seen_headers: set[str] = set()
                for header in headers:
                    if header in seen_headers:
                        raise ValueError(
                            "roofline.csv contains duplicate benchmark "
                            f"header {header!r}"
                        )
                    seen_headers.add(header)
                columns = {header: [] for header in headers}
                expected_width = len(headers) + 1
                continue

            if not row or all(cell.strip() == "" for cell in row):
                raise ValueError(f"roofline.csv row {row_number} is empty")

            if len(row) != expected_width:
                raise ValueError(
                    f"roofline.csv row {row_number} has {len(row)} columns, "
                    f"expected {expected_width}"
                )

            device_id = _parse_integral_id(row[0], label="device id")
            if device_id in seen_device_ids:
                raise ValueError(
                    f"roofline.csv contains duplicate device id {device_id}"
                )
            seen_device_ids.add(device_id)
            device_ids.append(device_id)
            for column_index, header in enumerate(headers):
                columns[header].append(row[column_index + 1])

    return RooflineCsvData(device_ids=device_ids, columns=columns)


def _parse_requested_device_id(value: Union[int, float, str]) -> int:
    """Validate and normalize a requested roofline device id."""
    device_id = _parse_integral_id(value, label="device_id")
    if device_id < 0:
        raise ValueError(f"device_id must be non-negative, got {device_id}")
    return device_id


def _resolve_device_row_index(
    csv_data: RooflineCsvData,
    requested_device_id: Union[int, float, str],
) -> int:
    """Return the unique CSV row index for a requested semantic device id."""
    device_id = _parse_requested_device_id(requested_device_id)
    matching_rows = [
        row_index
        for row_index, csv_device_id in enumerate(csv_data.device_ids)
        if csv_device_id == device_id
    ]
    if len(matching_rows) != 1:
        raise ValueError(
            f"device id {device_id} occurs {len(matching_rows)} times in roofline.csv"
        )
    return matching_rows[0]


def _parse_integral_id(value: Union[int, float, str], *, label: str) -> int:
    """Parse an integral device id from CSV cells or request parameters."""
    if isinstance(value, bool):
        raise ValueError(f"{label} must not be a boolean")
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        if not value.is_integer():
            raise ValueError(f"{label} must be an integral value, got {value}")
        return int(value)
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            raise ValueError(f"{label} must be an integral value, got empty string")
        try:
            numeric = float(stripped)
        except ValueError as error:
            raise ValueError(
                f"{label} must be an integral value, got {value!r}"
            ) from error
        if not numeric.is_integer():
            raise ValueError(f"{label} must be an integral value, got {value!r}")
        return int(numeric)
    raise ValueError(f"{label} must be an integral value, got {type(value).__name__}")


def _expected_benchmark_columns(
    roofline_parameters: dict[str, Any], dtype: str, mspec: MachineSpecs
) -> list[str]:
    """Benchmark columns the roofline needs for this datatype and mem levels."""
    ops_flops = "Ops" if dtype.startswith("I") else "Flops"
    columns: list[str] = []

    if OpsSupport.VALU in SUPPORTED_DATATYPES[mspec.gpu_arch][dtype]:
        columns.append(f"{dtype}{ops_flops}")

    cache_hierarchy = sanitize_mem_level(
        roofline_parameters["mem_level"], mspec.gpu_model
    )
    columns.extend(f"{cache_level}Bw" for cache_level in cache_hierarchy)

    if OpsSupport.MATRIX in SUPPORTED_DATATYPES[mspec.gpu_arch][dtype]:
        if dtype.startswith(("I", "B")):
            target_precision = dtype
        elif dtype.startswith("MX"):
            target_precision = f"MXF{dtype[4:]}"
        else:
            target_precision = f"F{dtype[2:]}"
        columns.append(
            f"{roofline_parameters['matrix_ops_type']}{target_precision}{ops_flops}"
        )
    return columns


def _device_values(
    benchmark_data: dict[str, list[str]],
    row_index: int,
    column_suffixes: tuple[str, ...],
) -> list[float]:
    """Collect positive finite values from columns ending in the given suffixes."""
    values: list[float] = []
    for column, rows in benchmark_data.items():
        if not any(column.endswith(suffix) for suffix in column_suffixes):
            continue
        sanitized = sanitize_ai_value(rows[row_index])
        if sanitized > 0:
            values.append(sanitized)
    return values
