---
performance:
  Performance_hipEventCreate: *level_stress
  Performance_hipEventCreateWithFlags: *level_stress
  Performance_hipEventRecord: *level_stress
  Performance_hipEventDestroy: *level_stress
  Performance_hipEventSynchronize: *level_stress
  Performance_hipEventElapsedTime: *level_stress
  Performance_hipEventQuery: *level_stress
  Performance_Example: *level_stress
  Performance_Triple_Chevron: *level_stress
  Performance_hipLaunchKernel: *level_stress
  Performance_hipLaunchCooperativeKernel: *level_stress
  Performance_hipExtLaunchKernel: *level_stress
  Performance_hipExtLaunchKernelGGL_QueryGPUFrequency:
    <<: *level_stress
    # Following tests disabled as it should be a local perf test
    disabled: [amd_linux, amd_windows, amd_wsl]
  Performance_hipMemcpy_DeviceToHost: *level_stress
  Performance_hipMemcpy_HostToDevice: *level_stress
  Performance_hipMemcpy_HostToHost: *level_stress
  Performance_hipMemcpy_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpy_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpyAsync_DeviceToHost: *level_stress
  Performance_hipMemcpyAsync_HostToDevice: *level_stress
  Performance_hipMemcpyAsync_HostToHost: *level_stress
  Performance_hipMemcpyAsync_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpyAsync_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpyWithStream_DeviceToHost: *level_stress
  Performance_hipMemcpyWithStream_HostToDevice: *level_stress
  Performance_hipMemcpyWithStream_HostToHost: *level_stress
  Performance_hipMemcpyWithStream_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpyWithStream_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpyAtoH:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpyHtoA:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpyBatchAsync_D2D: *level_stress
  Performance_hipMemcpyBatchAsync_P2P: *level_stress
  Performance_hipMemcpyBatchAsync_H2D_Pageable: *level_stress
  Performance_hipMemcpyBatchAsync_H2D_Pinned: *level_stress
  Performance_hipMemcpyBatchAsync_D2H_Pageable: *level_stress
  Performance_hipMemcpyBatchAsync_D2H_Pinned: *level_stress
  Performance_hipMemcpyDtoD_PeerAccessEnabled: *level_stress
  Performance_hipMemcpyDtoD_PeerAccessDisabled: *level_stress
  Performance_hipMemcpyDtoDAsync_PeerAccessEnabled: *level_stress
  Performance_hipMemcpyDtoDAsync_PeerAccessDisabled: *level_stress
  Performance_hipMemcpyDtoH: *level_stress
  Performance_hipMemcpyDtoHAsync: *level_stress
  Performance_hipMemcpyHtoD: *level_stress
  Performance_hipMemcpyHtoDAsync: *level_stress
  Performance_hipMemcpyHtoDKernelDtoHV1Async: *level_stress
  Performance_hipMemcpyHtoDKernelDtoHV2Async: *level_stress
  Performance_hipMemcpyToSymbol_SingularValue: *level_stress
  Performance_hipMemcpyToSymbol_ArrayValue: *level_stress
  Performance_hipMemcpyToSymbol_WithOffset: *level_stress
  Performance_hipMemcpyToSymbolAsync_SingularValue: *level_stress
  Performance_hipMemcpyToSymbolAsync_ArrayValue: *level_stress
  Performance_hipMemcpyToSymbolAsync_WithOffset: *level_stress
  Performance_hipMemcpyFromSymbol_SingularValue: *level_stress
  Performance_hipMemcpyFromSymbol_ArrayValue: *level_stress
  Performance_hipMemcpyFromSymbol_WithOffset: *level_stress
  Performance_hipMemcpyFromSymbolAsync_SingularValue: *level_stress
  Performance_hipMemcpyFromSymbolAsync_ArrayValue: *level_stress
  Performance_hipMemcpyFromSymbolAsync_WithOffset: *level_stress
  Performance_hipMemcpy2D_DeviceToHost: *level_stress
  Performance_hipMemcpy2D_HostToDevice: *level_stress
  Performance_hipMemcpy2D_HostToHost:
    <<: *level_stress
    # Below tests are failing PSDB
    disabled: [amd_windows]
  Performance_hipMemcpy2D_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpy2D_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpy2DAsync_DeviceToHost: *level_stress
  Performance_hipMemcpy2DAsync_HostToDevice: *level_stress
  Performance_hipMemcpy2DAsync_HostToHost:
    <<: *level_stress
    # Below tests are failing PSDB
    disabled: [amd_windows]
  Performance_hipMemcpy2DAsync_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpy2DAsync_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpy2DToArray_HostToDevice:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DToArray_DeviceToDevice_DisablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DToArray_DeviceToDevice_EnablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DToArrayAsync_HostToDevice:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DToArrayAsync_DeviceToDevice_DisablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DToArrayAsync_DeviceToDevice_EnablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DFromArray_DeviceToHost:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DFromArray_DeviceToDevice_DisablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DFromArray_DeviceToDevice_EnablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DFromArrayAsync_DeviceToHost:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DFromArrayAsync_DeviceToDevice_DisablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpy2DFromArrayAsync_DeviceToDevice_EnablePeerAccess:
    <<: *level_stress
    tags: [image]
  Performance_hipMemcpyParam2D_DeviceToHost: *level_stress
  Performance_hipMemcpyParam2D_HostToDevice: *level_stress
  Performance_hipMemcpyParam2D_HostToHost: *level_stress
  Performance_hipMemcpyParam2D_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpyParam2D_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpyParam2DAsync_DeviceToHost: *level_stress
  Performance_hipMemcpyParam2DAsync_HostToDevice: *level_stress
  Performance_hipMemcpyParam2DAsync_HostToHost: *level_stress
  Performance_hipMemcpyParam2DAsync_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpyParam2DAsync_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpy3D_DeviceToHost: *level_stress
  Performance_hipMemcpy3D_HostToDevice: *level_stress
  Performance_hipMemcpy3D_HostToHost: *level_stress
  Performance_hipMemcpy3D_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpy3D_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemcpy3DAsync_DeviceToHost: *level_stress
  Performance_hipMemcpy3DAsync_HostToDevice: *level_stress
  Performance_hipMemcpy3DAsync_HostToHost: *level_stress
  Performance_hipMemcpy3DAsync_DeviceToDevice_DisablePeerAccess: *level_stress
  Performance_hipMemcpy3DAsync_DeviceToDevice_EnablePeerAccess: *level_stress
  Performance_hipMemset: *level_stress
  Performance_hipMemsetAsync: *level_stress
  Performance_hipMemsetD8: *level_stress
  Performance_hipMemsetD8Async: *level_stress
  Performance_hipMemsetD16:
    <<: *level_stress
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemsetD16Async:
    <<: *level_stress
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemsetD32:
    <<: *level_stress
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemsetD32Async:
    <<: *level_stress
    # Below tests tests fail in PSDB
    disabled: [nvidia_windows]
  Performance_hipMemset2D: *level_stress
  Performance_hipMemset2DAsync: *level_stress
  Performance_hipMemset3D: *level_stress
  Performance_hipMemset3DAsync: *level_stress
  Performance_hipStreamWaitEvent: *level_stress
  Performance_hipStreamGetFlags: *level_stress
  Performance_hipStreamGetPriority: *level_stress
  Performance_hipExtStreamCreateWithCUMask: *level_stress
  Performance_hipExtStreamGetCUMask: *level_stress
  Performance_hipStreamAddCallback: *level_stress
  Performance_hipStreamWaitValue32: *level_stress
  Performance_hipStreamWaitValue64: *level_stress
  Performance_hipStreamWriteValue32: *level_stress
  Performance_hipStreamWriteValue64: *level_stress
  Performance_hipMallocAsync: *level_stress
  Performance_hipFreeAsync: *level_stress
  Performance_hipMemPoolCreate: *level_stress
  Performance_hipMemPoolDestroy: *level_stress
  Performance_hipMemPoolTrimTo: *level_stress
  Performance_hipMemPoolSetAttribute: *level_stress
  Performance_hipMemPoolGetAttribute: *level_stress
  Performance_hipMemPoolSetAccess: *level_stress
  Performance_hipMallocFromPoolAsync: *level_stress
  Performance_hipMemPoolExportToShareableHandle: *level_stress
  Performance_hipMemPoolGetAccess: *level_stress
  Performance_hipMemPoolImportFromShareableHandle: *level_stress
  Performance_hipMemPoolExportPointer: *level_stress
  Performance_hipMemPoolImportPointer: *level_stress
  Performance_hipStreamCreate: *level_stress
  Performance_hipStreamCreateWithFlags: *level_stress
  Performance_hipStreamCreateWithPriority: *level_stress
  Performance_hipStreamDestroy: *level_stress
  Performance_hipDeviceGetStreamPriorityRange: *level_stress
  Performance_hipStreamQuery: *level_stress
  Performance_hipStreamSynchronize: *level_stress
  Performance_SplitBarrier_ImbalancedWorkgroup: *level_stress
  Performance_Reduce_Sync_Add: *level_stress
  Performance_Reduce_Sync_Min: *level_stress
  Performance_Reduce_Sync_Max: *level_stress
  Performance_Reduce_Sync_And: *level_stress
  Performance_Reduce_Sync_Or: *level_stress
  Performance_Reduce_Sync_Xor: *level_stress
  Performance_hipPerfDotProduct: *level_stress
  Performance_hipPerfMandelbrot: *level_stress
  Performance_hipPerfDispatchAndExecutionSpeed: *level_stress
  Performance_hipKernelLookup: *level_stress
  Performance_hipEventOverflow: *level_stress
  Performance_GraphWithMoreAllocFreeNodes_SingleBranchNoOperations: *level_stress
  Performance_GraphWithMoreAllocFreeNodes_SerialNodesSingleBranchWithOps: *level_stress
  Performance_GraphWithMoreAllocFreeNodes_MultipleBranches: *level_stress
  Performance_GraphWithMoreAllocFreeNodes_MultipleIndependentBranches: *level_stress
  Performance_GraphWithMoreAllocFreeNodes_OneBranchNoOps_AutoFreeOnLaunch: *level_stress
  Performance_hipGraph_ParallelGraph: *level_stress
  Performance_hipGraph_WithStreamOperations: *level_stress
  Performance_hipGraph_WithStreamCapture: *level_stress
  Performance_GraphTopology_Straight: *level_stress
  Performance_GraphTopology_Parallel: *level_stress
  Performance_GraphTopology_Hexagon: *level_stress
  Performance_GraphTopology_Mixed: *level_stress
  Performance_GraphExecUpdate_Linear: *level_stress
  Performance_PyFR_Couette_IndividualGraphs: *level_stress
  Performance_PyFR_Couette_StepSimulation: *level_stress
  Performance_PyFR_Couette_SingleIteration: *level_stress
  Performance_hipPerfMemcpy_test: *level_stress
  Performance_hipPerfBufferCopyRectSpeed_test: *level_stress
  Performance_hipPerfBufferCopySpeed_test: *level_stress
  Performance_hipPerfDevMemReadSpeed_test: *level_stress
  Performance_hipPerfDevMemWriteSpeed_test: *level_stress
  Performance_hipPerfMemFill_test: *level_stress
  Performance_hipPerfMemMallocCpyFree_test: *level_stress
  Performance_hipPerfMemset_test: *level_stress
  Performance_hipPerfSampleRate_test: *level_stress
  Performance_hipPerfSharedMemReadSpeed_test: *level_stress
  Performance_hipTestP2PUniDirMemcpyAsync_test_Timing_CPU: *level_stress
  Performance_hipTestP2PUniDirMemcpyAsync_test_Timing_GPU: *level_stress
  Performance_hipTestP2PUniDirKernelCopy_test_Timing_CPU: *level_stress
  Performance_hipTestP2PUniDirKernelCopy_test_Timing_GPU: *level_stress
  Performance_hipTestP2PBiDirMemcpyAsync_test: *level_stress
  Performance_hipTestP2PBiDirKernelCopy_test: *level_stress
  Performance_hipCheckP2PSupport: *level_stress
  Performance_PerfBufferCopySpeedAll2All_test_hipMemcpyPeerAsync_remotes_to_local: *level_stress
  Performance_PerfBufferCopySpeedAll2All_test_hipMemcpyPeerAsync_local_to_remotes: *level_stress
  Performance_PerfBufferCopySpeedAll2All_test_kernel_copy_remotes_to_local: *level_stress
  Performance_PerfBufferCopySpeedAll2All_test_kernel_copy_local_to_remotes: *level_stress
  Performance_PerfBufferCopySpeedAll2One_test_hipMemcpyPeerAsync_remotes_to_local: *level_stress
  Performance_PerfBufferCopySpeedOne2All_test_hipMemcpyPeerAsync_local_to_remotes: *level_stress
  Performance_PerfBufferCopySpeedAll2One_test_kernel_copy_remotes_to_local: *level_stress
  Performance_PerfBufferCopySpeedOne2All_test_kernel_copy_local_to_remotes: *level_stress
  Performance_MempoolManager_hipMallocAsync_hipFreeAsync: *level_stress
  Performance_DeviceHeapMemoryAllocation: *level_stress
  Performance_PerfBufferCopySpeedAll2All_Inter_GPU: *level_stress
  Performance_hipPerfMemcpyAsyncSpeed_test: *level_stress
  Performance_hipPerfMemsetAsyncSpeed_test: *level_stress
  Performance_hipPerfHostNumaAlloc_test: *level_stress
  Performance_hipPerfDeviceConcurrency: *level_stress
  Performance_hipPerfStreamConcurrency: *level_stress
  Performance_hipPerfStreamCreateCopyDestroy: *level_stress
  Performance_KernelLaunchLatency_IncreasingNumberOfStreams: *level_stress
  Performance_hipPerfMultiStreamKernelLaunch: *level_stress
  Performance_hipPerfVMMAllocSpeed_test: *level_stress
  Performance_hipPerfHostNumaAlloc_test_preferred_host_numa_node_on_each_GPU: *level_stress
  Performance_Graph_CollapseCorrectness: *level_stress
  Performance_Graph_DisabledBoundarySynchronization: *level_stress
  Performance_hipPerfSharedQueueAnyOrderOverlap: *level_stress
  Performance_hipPerfSharedQueueAnyOrderOverlap_EventDependency: *level_stress
