/*************************************************************************
 * Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

// Host-only dependency floor for src/rccl_wrap.cc's microtest, compiled
// into rccl-UnitTestsMicro alongside p2p.cc/rma_proxy_progress.cc's own
// tests. #include-ing the whole 1773-line rccl_wrap.cc (via WRAP_CC_PATH)
// pulls in the DDA / CE / symmetric-kernel / hierarchical backend-selection
// machinery even though the covered functions (see wrap-test.cc) don't reach
// all of it yet. Everything below satisfies the link closure. Controllable
// seams use conservative production-like defaults; tests override them with
// ScopedHook when a branch needs different behaviour.
//
// Dependencies with an established owner live in their canonical fake files:
// collectives_fakes, strongstream_stubs, ce_fakes, sym_kernels_fakes,
// transport_stubs, and tuning_fakes. dev_runtime.cc is now another unit under
// test in this binary, so its real window lookup/predicate functions satisfy
// rccl_wrap.cc directly. This file contains only the remaining rccl_wrap.cc
// link-closure seams that have no shared owner yet. nccl_stubs.cc is not linked
// because it defines commSetUnrollFactor, which is a real function supplied by
// the unit under test itself.
//
// RCCL_PARAM / NCCL_PARAM: every RCCL_PARAM(...) invocation textually inside
// rccl_wrap.cc is redirected by wrap-test.cc to route through a g_loadParam
// std::function hook (same mechanism as init-test.cc's redirect), so a test
// can flip one param's value between cases -- see wrap-test.cc's redirector
// comment. The few ncclParamXxx / rcclParamXxx symbols rccl_wrap.cc declares
// `extern` and calls without a local RCCL_PARAM/NCCL_PARAM invocation (their
// generator lives in another .cc) are stubbed below instead.

#include "wrap_fakes.h"

#include <cstdint>
#include <functional>

#include "amdsmi_wrap.h"
#include "ce_coll.h"
#include "comm.h"
#include "debug.h"
#include "dev_runtime.h"
#include "enqueue.h"
#include "group.h"
#include "nccl.h"
#include "rccl_common.h"
#ifdef ENABLE_ROCSHMEM_GIN
#include "algorithms/gin/gin_all_reduce.h"
#endif
#include "signature-drift.h"
#include "strongstream.h"
#include "sym_kernels.h"

ASSERT_HOOK_MATCHES_PROD(g_amdSmiGetFirmwareVersion, amd_smi_getFirmwareVersion);
ASSERT_HOOK_MATCHES_PROD(g_isSymmetricKernelRequested, isSymmetricKernelRequested);
ASSERT_HOOK_MATCHES_PROD(g_allReduceShouldTakeDdaPath, rcclAllReduceShouldTakeDdaPath);
ASSERT_HOOK_MATCHES_PROD(g_commCount, ncclCommCount);

// getAlgoInfo, rcclKernelPackedChannels, and the four ReduceScatter *Blocks
// hooks are link-closure symbols with no production header declaration, so
// there is no header-visible signature to pin here.

#undef ASSERT_HOOK_MATCHES_PROD

// ---------------------------------------------------------------------------
// Logging infrastructure. WARN/INFO (debug.h) expand to ncclDebugLog(); three
// of the units under test (rcclGetAlgoProtoIndex, rcclGetAlgoName,
// rcclGetProtocolName) call WARN on their invalid-input arms, and tests assert
// on that text via gtest's stderr capture.
//
// ncclDebugLevel / ncclDebugMask / ncclDebugNoWarn / ncclDebugLog() itself
// are defined once, by fakes/nccl_fakes.cc, which this binary already links
// for p2p.cc's tests -- defining them again here would be a duplicate-symbol
// error. ncclDebugMask's default there (0) differs from what this file used
// when it was its own standalone binary (~0ULL). WARN(...) calls
// ncclDebugLog() unconditionally regardless of mask; INFO(...) call sites are
// tested with explicit ScopedDebugLogging settings in wrap-test.cc rather
// than relying on either fake's default.
// ---------------------------------------------------------------------------
FILE* ncclDebugFile = nullptr;
char  ncclLastError[1024] = {};

// ---------------------------------------------------------------------------
// ncclParamXxx / rcclParamXxx symbols NOT generated by an RCCL_PARAM/NCCL_PARAM
// invocation inside rccl_wrap.cc itself (see file header comment). Trivial
// real behaviour (return the production default) rather than abort(): these
// are read on essentially every call into the file's channel/DDA tuning
// paths, so an abort-floor here would make even unrelated tests crash before
// reaching the function they actually meant to exercise.
//
// Unlike NCCL_NUM_ALGORITHMS/ncclNumFuncs below, there's no importable
// constant for "the current default" here -- NCCL_PARAM/RCCL_PARAM bakes
// deftVal directly as an inline macro-argument literal (see param.h), not a
// separately declared symbol, so a static_assert can't check it. CMakeLists.txt
// checks the invocation text against the original sources at configure time,
// when those files are guaranteed to be available.
// ---------------------------------------------------------------------------
static int64_t DefaultParamForceCe() { return 1; }  // enqueue/enqueue.cc:4108
std::function<int64_t()> g_paramForceCe = DefaultParamForceCe;
int64_t rcclParamForceCe() { return g_paramForceCe(); }

// init.cc owns NCCL_PARAM(P2pDisable), but rccl_wrap.cc consults its accessor
// while applying gfx120x protocol tuning. Keep the production default and let
// the protocol test override it explicitly.
static int64_t DefaultParamP2pDisable() { return 0; }  // init.cc:137
std::function<int64_t()> g_paramP2pDisable = DefaultParamP2pDisable;
int64_t ncclParamP2pDisable() { return g_paramP2pDisable(); }

// The settable env-var fake (SetMicroEnv/SetMicroEnvAbsent/ClearMicroEnv,
// the bare-getenv() link-level interposer, and ncclGetEnv) is NOT defined
// here: fakes/env_fakes.cc is the shared owner of src/misc/param.cc + getenv
// interposition for every microtest binary (see MICROTEST_README.md's
// "Where a fake belongs"). rccl_wrap.cc's several bare getenv() call sites
// (rcclSetPxn, rcclSetP2pNetChunkSize, rcclUpdateCollectiveProtocol,
// rcclUpdateThreadThreshold, ...) are covered by that same interposer.
// ncclGroupDepth is NOT faked here: group-test.cc (also part of this binary
// since the rccl-UnitTestsMicro merge) compiles the real group.cc, which
// defines it -- a second copy here would be a duplicate-symbol error. Its
// real default (0, "not grouped") is what every rccl_wrap.cc test so far
// assumes, same as when this was a hand-copied stub.

// ncclDevFuncUnrollGenerated: extern bool const[NCCL_NUM_UNROLLS]. Real array,
// not abort-floor -- commSetUnrollFactor indexes it unconditionally on every
// call, including the manual-override path the commSetUnrollFactor tests
// exercise. All-true is the safe default: "every unroll factor was built".
//
// Confirmed NOT safely upgradeable to a test seam: device.h's `extern bool
// const [...]` declaration is transitively visible in this TU too (this
// file doesn't include device.h directly, but something in its include
// chain does) -- dropping `const` here is a hard redefinition-with-
// different-type compile error, not just a lurking runtime risk. Leaving
// this const and documented, not forced through.
//
// Drift watchdog: without one, a new unroll factor added to RCCL would not be
// caught here -- the extra array slot would silently zero-initialize to false,
// quietly changing behavior. The check is a RUNTIME test
// (FakeTableDrift_UnrollCountMatchesProduction in wrap-test.cc), not a
// static_assert, for the same reason as the enum-count checks below.
const bool ncclDevFuncUnrollGenerated[NCCL_NUM_UNROLLS] = {true, true, true, true, true, true};

// A nullptr means an unroll factor is not restricted to a single architecture.
// The generated production table is build-target-specific; the host-only test
// build intentionally models the unrestricted case for every generated entry.
char const* const ncclDevFuncUnrollArch[NCCL_NUM_UNROLLS] = {};

// ncclCommCount: real behaviour by default (de-risks future tests),
// but a controllable seam so rcclGetAlgoInfo's NCCLCHECK(ncclCommCount(...))
// failure arm (never exercised -- every prior test let this succeed) can be
// proven too.
static ncclResult_t DefaultCommCount(const ncclComm_t comm, int* count) {
  if (count) *count = comm ? comm->nRanks : 0;
  return ncclSuccess;
}
std::function<ncclResult_t(const ncclComm_t, int*)> g_commCount = DefaultCommCount;
ncclResult_t ncclCommCount(const ncclComm_t comm, int* count) { return g_commCount(comm, count); }

// ---------------------------------------------------------------------------
// Controllable seams for the top-level dispatchers (rcclSelectAllReduce/
// AllGather/ReduceScatter, rcclHierarchicalAlgoInfo, rcclGetAlgoInfo,
// rcclGetCollImplInfo, rcclSymkQuery/rcclSymKGetInfo's deep path). Without
// these each would have exactly one reachable outcome (see
// MICROTEST_README.md, "Adding more controllable
// seams" for the pattern followed here); upgraded so wrap-test.cc can drive
// each branch of those dispatchers directly. Every default below reproduces
// the safe, common "this fast path doesn't apply" case so existing tests
// upstream of these seams are unaffected -- verified by rereading each real
// call site before choosing it.
// ---------------------------------------------------------------------------

#ifdef ENABLE_ROCSHMEM_GIN
// The real definitions live in gin_alltoall_sdma.cu / gin_all_reduce_sdma.cu,
// which this host-only binary intentionally does not compile. Keep GIN-SDMA
// out of the selector by default so ENABLE_ROCSHMEM_GIN builds retain the
// non-GIN test behaviour.
bool ncclAllToAllGinSdmaEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t) {
  return false;
}

bool ncclAllReduceGinSdmaEligible(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}

bool ncclAllReduceGinSdmaYieldToDda(ncclComm*, const void*, void*, size_t, ncclDataType_t, ncclRedOp_t) {
  return false;
}
#endif

// Drives `symEligible` in all three rcclSelectXxx functions. Default false:
// "no symmetric-window kernel requested," letting the DDA/CE/Direct/plain
// paths run, matching every existing (guard-only) test's expectations.
static bool DefaultIsSymmetricKernelRequested(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, const void*,
                                              void*, bool) {
  return false;
}
std::function<bool(struct ncclComm*, ncclFunc_t, int, ncclDataType_t, size_t, const void*, void*, bool)>
    g_isSymmetricKernelRequested = DefaultIsSymmetricKernelRequested;
bool isSymmetricKernelRequested(struct ncclComm* comm, ncclFunc_t coll, int symkOp, ncclDataType_t datatype,
                                size_t nElts, const void* sendbuff, void* recvbuff, bool agreeAcrossRanks) {
  return g_isSymmetricKernelRequested(comm, coll, symkOp, datatype, nElts, sendbuff, recvbuff, agreeAcrossRanks);
}

// The window-taking twin: rcclSelectXxx hoists the ncclDevrFindWindow lookups
// and asks this one, so it drives `symEligible` on every path a fixture can
// reach. Routed through the SAME seam rather than a second hook so one
// ScopedHook still controls the decision; the windows stand in for the buffers,
// which no fixture inspects. agreeAcrossRanks is false because the production
// window overload is the rank-local check (its caller does the agreement).
bool isSymmetricKernelRequestedWin(struct ncclComm* comm, ncclFunc_t coll, int symkOp, ncclDataType_t datatype,
                                   size_t nElts, struct ncclDevrWindow* sendWin, struct ncclDevrWindow* recvWin) {
  return g_isSymmetricKernelRequested(comm, coll, symkOp, datatype, nElts, sendWin, recvWin,
                                      /*agreeAcrossRanks=*/false);
}

// rcclAllReduceShouldTakeDdaPath: real body lives in collectives.cc (not
// linked here), same abort-floor-turned-seam treatment as the rest. Default
// false: DDA not taken, letting CE-registered/symmetric/plain-kernel run.
static bool DefaultAllReduceShouldTakeDdaPath(const struct ncclComm*, size_t, ncclDataType_t, bool, bool, bool) {
  return false;
}
std::function<bool(const struct ncclComm*, size_t, ncclDataType_t, bool, bool, bool)> g_allReduceShouldTakeDdaPath =
    DefaultAllReduceShouldTakeDdaPath;
bool rcclAllReduceShouldTakeDdaPath(const struct ncclComm* comm, size_t count, ncclDataType_t dt, bool symEligible,
                                    bool ceAllReduceAllowed, bool query) {
  return g_allReduceShouldTakeDdaPath(comm, count, dt, symEligible, ceAllReduceAllowed, query);
}

// getAlgoInfo / rcclKernelPackedChannels: rccl_wrap.cc `extern`-declares both
// itself (their real definitions live in enqueue.cc / device-side tuning,
// outside this TU's link closure), so no separate declaration is needed here.
// Default getAlgoInfo fills in a sane, generic Ring/Simple/1-channel answer
// (the universal plain-kernel fallback every rcclSelectXxx eventually falls
// to); default rcclKernelPackedChannels passes the tuning-cap channel count
// through unpacked, a safe no-op default.
static ncclResult_t DefaultGetAlgoInfo(struct ncclComm*, struct ncclTaskColl* task, int, int, int, ncclSimInfo_t*) {
  task->algorithm = NCCL_ALGO_RING;
  task->protocol = NCCL_PROTO_SIMPLE;
  task->nMaxChannels = 1;
  return ncclSuccess;
}
std::function<ncclResult_t(struct ncclComm*, struct ncclTaskColl*, int, int, int, ncclSimInfo_t*)> g_getAlgoInfo =
    DefaultGetAlgoInfo;
ncclResult_t getAlgoInfo(struct ncclComm* comm, struct ncclTaskColl* task, int collNetSupport, int nvlsSupport,
                         int numPipeOps, ncclSimInfo_t* simInfo) {
  return g_getAlgoInfo(comm, task, collNetSupport, nvlsSupport, numPipeOps, simInfo);
}

static int DefaultKernelPackedChannels(struct ncclComm*, ncclFunc_t, size_t, ncclDataType_t, int, int nMaxChannels) {
  return nMaxChannels;
}
std::function<int(struct ncclComm*, ncclFunc_t, size_t, ncclDataType_t, int, int)> g_kernelPackedChannels =
    DefaultKernelPackedChannels;
int rcclKernelPackedChannels(struct ncclComm* comm, ncclFunc_t func, size_t count, ncclDataType_t dt, int protocol,
                             int nMaxChannels) {
  return g_kernelPackedChannels(comm, func, count, dt, protocol, nMaxChannels);
}

// rcclLL128ElemsPerThreadFromArch is `inline` in archinfo.h (transitively
// included), so no stub is needed here.

// getFirmwareVersion()'s sole dependency. Settable hook, same std::function
// shape as fakes/nccl_fakes.cc's, so a test can script a canned firmware
// response or a failure without touching the real AMD-SMI layer.
static ncclResult_t DefaultAmdSmiGetFirmwareVersion(uint32_t /*devIdx*/, uint64_t* fwVersion) {
  *fwVersion = 0;
  return ncclSuccess;
}
std::function<ncclResult_t(uint32_t, uint64_t*)> g_amdSmiGetFirmwareVersion = DefaultAmdSmiGetFirmwareVersion;
ncclResult_t amd_smi_getFirmwareVersion(uint32_t devIdx, uint64_t* fwVersion) {
  return g_amdSmiGetFirmwareVersion(devIdx, fwVersion);
}
