---
context:
  Unit_hipDeviceGetPCIBusId_Functional: *level_default
  Unit_hipDrvMemcpy_Functional:
    <<: *level_default
    tags: [memory, transfer]
  Unit_hipMemsetD8_Functional:
    <<: *level_default
    tags: [memory, memset]
  Unit_hipDevicePrimaryCtxSetFlags_Negative: *level_default
  Unit_hipDeviceAPIs_not_supported: *level_default
  Unit_hipCtxGetSetCacheConfig_not_supported: *level_default
  Unit_hipCtxGetSetSharedMemConfig_not_supported: *level_default
  Unit_hipCtxPeerAccess_not_supported: *level_default
  Unit_hipCtxAPIs_not_supported: *level_default
  Unit_hipDevicePrimaryCtxGetState_Negative: *level_default
  Unit_hipSetDevice_CheckPrimaryCtxState: *level_default
