---
errorHandling:
  Unit_hipGetErrorName_Positive_Basic:
    <<: *level_default
    tags: [smoke, P0]
  Unit_hipGetErrorName_Negative_Parameters: *level_default
  Unit_hipGetErrorString_Positive_Basic:
    <<: *level_default
    tags: [smoke, P0]
  Unit_hipGetErrorString_Negative_Parameters: *level_default
  Unit_hipDrvGetErrorName_Positive_Basic: *level_default
  Unit_hipDrvGetErrorName_Negative_Parameters: *level_default
  Unit_hipDrvGetErrorString_Positive_Basic: *level_default
  Unit_hipDrvGetErrorString_Negative_Parameters: *level_default
  Unit_hipGetLastError_Positive_Basic:
    <<: *level_default
    tags: [smoke, P0]
  Unit_hipGetLastError_Positive_Threaded: *level_default
  Unit_hipGetLastError_with_hipMemcpyPeerAsync:
    <<: *level_default
    tags: [multigpu]
  Unit_hipGetLastError_with_hipMemcpyDtoHAsync: *level_default
  Unit_hipGetLastError_with_hipMemcpyParam2DAsync:
    <<: *level_default
    disabled: [amd_wsl]
  Unit_hipGetLastError_with_hipDrvMemcpy3DAsync: *level_default
  Unit_hipGetLastError_with_hipMemcpy3DAsync:
    <<: *level_default
    tags: [image]
  Unit_hipGetLastError_with_hipMemcpy2D_To_From_ArrayAsync: *level_default
  Unit_hipGetLastError_with_hipStreamAttachMemAsync: *level_default
  Unit_hipGetLastError_with_hipWaitExternalSemaphoresAsync: *level_default
  Unit_hipGetLastError_with_hipSignalExternalSemaphoresAsync: *level_default
  Unit_hipGetLastError_with_hipMemPrefetchAsync: *level_default
  Unit_hipGetLastError_with_hipMemcpy2DAsync:
    <<: *level_default
    disabled: [amd_wsl]
  Unit_hipGetLastError_with_hipMemsetAsync: *level_default
  Unit_hipGetLastError_with_MemCpyAsync: *level_default
  Unit_hipGetLastError_with_MemCpyAsync_thread: *level_default
  Unit_hipGetLastError_with_hipGraphAddMemcpyNode1D: *level_default
  Unit_hipGetLastError_with_hipStreamBegin_EndCapture: *level_default
  Unit_hipGetLastError_success_before_hipGetLastError: *level_default
  Unit_hipGetLastError_success_before_hipGetLastError_check_again: *level_default
  Unit_hipGetLastError_with_Kernel_divide_by_zero: *level_default
  Unit_hipGetLastError_with_Kernel_Invalid_Configuration: *level_default
  Unit_hipGetLastError_With_Chk_Updated_Status: *level_default
  Unit_hipGetLastError_Chk_Along_hipPeekAtLastError: *level_default
  Unit_hipGetLastError_Error_Combinations: *level_default
  Unit_hipGetLastError_With_Thread: *level_default
  Unit_hipGetLastError_MultiProcess: *level_default
  Unit_hipGetLastError_Kernel_Invalid_Config: *level_default
  Unit_hipPeekAtLastError_Positive_Basic:
    <<: *level_default
    tags: [smoke, P0]
  Unit_hipPeekAtLastError_Positive_Threaded: *level_default
  Unit_hipPeekAtLastError_Positive: *level_default
  Unit_hipPeekAtLastError_Chk_Updated_Status: *level_default
  Unit_hipPeekAtLastError_Chk_Along_hipGetLastError: *level_default
  Unit_hipPeekAtLastError_Error_Combinations: *level_default
  Unit_hipPeekAtLastError_With_Thread: *level_default
  Unit_hipPeekAtLastError_MultiProcess: *level_default
  Unit_hipPeekAtLastError_Kernel_Invalid_Config: *level_default
  Unit_hipGetLastError_KernelFailure_ValidAndInvalidOperations: *level_default
  Unit_hipGetLastError_KernelFailure_TwoDevices:
    <<: *level_default
    tags: [multigpu]
  Unit_hipGetLastError_KernelFailure_TwoStreams:
    <<: *level_default
    # Test causes error state in the runtime and prevents resource cleanup.
    disabled: [asan]
  Unit_hipExtGetLastError_Positive_Basic:
    <<: *level_default
    tags: [P0]
  Unit_hipExtGetLastError_Positive_Threaded: *level_default
  Unit_hipExtGetLastError_with_hipMemcpyPeerAsync:
    <<: *level_default
    tags: [multigpu]
  Unit_hipExtGetLastError_with_hipMemcpyDtoHAsync: *level_default
  Unit_hipExtGetLastError_with_hipMemcpyParam2DAsync:
    <<: *level_default
    disabled: [amd_wsl]
  Unit_hipExtGetLastError_with_hipDrvMemcpy3DAsync: *level_default
  Unit_hipExtGetLastError_with_hipMemcpy3DAsync:
    <<: *level_default
    tags: [image]
  Unit_hipExtGetLastError_with_hipMemcpy2D_To_From_ArrayAsync: *level_default
  Unit_hipExtGetLastError_with_hipStreamAttachMemAsync: *level_default
  Unit_hipExtGetLastError_with_hipWaitExternalSemaphoresAsync: *level_default
  Unit_hipExtGetLastError_with_hipSignalExternalSemaphoresAsync: *level_default
  Unit_hipExtGetLastError_with_hipMemPrefetchAsync: *level_default
  Unit_hipExtGetLastError_with_hipMemcpy2DAsync:
    <<: *level_default
    disabled: [amd_wsl]
  Unit_hipExtGetLastError_with_hipMemsetAsync: *level_default
  Unit_hipExtGetLastError_with_MemCpyAsync: *level_default
  Unit_hipExtGetLastError_with_MemCpyAsync_thread: *level_default
  Unit_hipExtGetLastError_with_hipGraphAddMemcpyNode1D: *level_default
  Unit_hipExtGetLastError_with_hipStreamBegin_EndCapture: *level_default
  Unit_hipExtGetLastError_success_before_error_check_again: *level_default
  Unit_hipExtGetLastError_with_Kernel_divide_by_zero: *level_default
  Unit_hipDynamicLogging_Positive_Basic:
    <<: *level_default
    # Following tests disabled as it should be a local perf test
    disabled: [amd_windows, amd_wsl]
  Unit_hipDynamicLogging_Positive_MultipleEnableDisable:
    <<: *level_default
    # Following tests disabled as it should be a local perf test
    disabled: [amd_windows, amd_wsl]
