---
event:
  Unit_hipEventCreate_NullCheck:
    <<: *level_default
    tags: [lifecycle, P1]
  Unit_hipEventCreateWithFlags_NullCheck:
    <<: *level_default
    tags: [lifecycle, P1]
  Unit_hipEventCreate_IncompatibleFlags:
    <<: *level_default
    tags: [lifecycle, P1]
  Unit_hipEventSynchronize_NullCheck:
    <<: *level_default
    tags: [synchronization, P1]
  Unit_hipEventQuery_NullCheck:
    <<: *level_default
    tags: [synchronization, P1]
  Unit_hipEventDestroy_NullCheck:
    <<: *level_default
    tags: [lifecycle, P1]
  Unit_hipEvent:
    <<: *level_default
    # SWDEV-411303 fails in WSL. Profiling not support in WSL
    disabled: [amd_wsl]
    tags: [synchronization, P0]
  Unit_hipEventElapsedTime_NullCheck:
    <<: *level_default
    tags: [synchronization, P1]
  Unit_hipEventElapsedTime_DisableTiming:
    <<: *level_default
    tags: [synchronization, P1]
  Unit_hipEventElapsedTime_DifferentDevices:
    <<: *level_default
    tags: [multigpu, synchronization, P1]
  Unit_hipEventElapsedTime_NotReady_Negative:
    <<: *level_default
    # SWDEV-411303 fails in WSL. Profiling not support in WSL
    disabled: [amd_wsl]
    tags: [synchronization, P1]
  Unit_hipEventElapsedTime:
    <<: *level_default
    tags: [synchronization, smoke, P0]
  Unit_hipEventElapsedTime_Verify_Capture:
    <<: *level_default
    tags: [synchronization]
  Unit_hipEventRecord:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
    tags: [synchronization, smoke, P0]
  Unit_hipEventRecord_Negative:
    <<: *level_default
    tags: [synchronization, P1]
  Unit_hipEventIpc:
    <<: *level_default
    # (amd_wsl) Below tests fail in stress test on 24/07/23
    disabled: [amd_windows, amd_wsl]
    tags: [ipc, P1]
  Unit_hipEventIpc_DestroyNonBlocking:
    <<: *level_default
    tags: [ipc, lifecycle]
  Unit_hipEventDestroy_Unfinished:
    <<: *level_default
    # SWDEV-411303 fails in WSL. Profiling not support in WSL
    disabled: [amd_wsl]
    tags: [lifecycle, P0]
  Unit_hipEventDestroy_WithWaitingStream:
    <<: *level_default
    # SWDEV-402054 fails in external github build
    disabled: [amd_windows, amd_wsl]
    tags: [lifecycle, P1]
  Unit_hipEventDestroy_Negative:
    <<: *level_default
    tags: [lifecycle, P1]
  Unit_hipEventDestroy_Verify_Capture:
    <<: *level_default
    tags: [lifecycle]
  Unit_hipEventCreate_Positive:
    <<: *level_default
    tags: [lifecycle, smoke, P0]
  Unit_hipEventCreate_Verify_Capture:
    <<: *level_default
    tags: [lifecycle]
  Unit_hipEventCreateWithFlags_Positive:
    <<: *level_default
    tags: [lifecycle, P0]
  Unit_hipEventCreateWithFlags_DisableSystemFence_HstVisMem:
    <<: *level_default
    # Note: intermittent Seg fault failure
    disabled: [amd_windows, amd_wsl]
    tags: [lifecycle, P1]
  Unit_hipEventCreateWithFlags_DefaultFlg_HstVisMem:
    <<: *level_default
    # Note: intermittent Seg fault failure
    disabled: [amd_windows, amd_wsl]
    tags: [lifecycle, P0]
  Unit_hipEventCreateWithFlags_DisableSystemFence_NonCohHstMem:
    <<: *level_default
    # Note: intermittent Seg fault failure
    disabled: [amd_windows, amd_wsl]
    tags: [lifecycle, P1]
  Unit_hipEventCreateWithFlags_DefaultFlg_NonCohHstMem:
    <<: *level_default
    # Note: intermittent Seg fault failure
    disabled: [amd_windows, amd_wsl]
    tags: [lifecycle, P1]
  Unit_hipEventCreateWithFlags_DisableSystemFence_CohHstMem:
    <<: *level_default
    # (amd_linux) SWDEV-470751 : Fine Grain memory is MTYPE_NC due to HW bug.
    # (amd_windows) Note: intermittent Seg fault failure
    disabled: [gfx1200, gfx1201, amdgcnspirv, amd_windows, amd_wsl]
    tags: [lifecycle, P1]
  Unit_hipEventCreateWithFlags_DefaultFlg_CohHstMem:
    <<: *level_default
    # Note: intermittent Seg fault failure
    disabled: [amd_windows, amd_wsl]
    tags: [lifecycle, P1]
  Unit_hipEventCreateWithFlags_Verify_Capture:
    <<: *level_default
    tags: [lifecycle]
  Unit_hipEventSynchronize_Default_Positive:
    <<: *level_default
    tags: [synchronization, smoke, P0]
  Unit_hipEventSynchronize_NoEventRecord_Positive:
    <<: *level_default
    tags: [synchronization, P0]
  Unit_hipEventMGpuMThreads_1:
    <<: *level_default
    tags: [synchronization, P1]
  Unit_hipEventMGpuMThreads_2:
    <<: *level_default
    tags: [multigpu, P1]
  Unit_hipEventMGpuMThreads_3:
    <<: *level_default
    tags: [multigpu, P1]
  Unit_hipEventQuery_DifferentDevice:
    <<: *level_default
    tags: [synchronization, P0]
  Unit_hipEventIpc_shm_cleanup:
    <<: *level_default
    tags: [ipc]
  Unit_hipEventCoalescing_CrossStreamWait:
    <<: *level_default
    tags: [synchronization]
  Unit_hipEventCoalescing_AsyncOpsBreakCoalescing:
    <<: *level_default
    tags: [synchronization]
  Unit_hipEventCoalescing_InterleavedEvents:
    <<: *level_default
    tags: [synchronization]
  Unit_hipEventCoalescing_EventQuery:
    <<: *level_default
    tags: [synchronization]
