---
kernel:
  Unit_hipMemFaultStackAllocation_Check:
    <<: *level_default
    tags: [memory, P1]
  Unit_hipLaunchBounds_With_maxThreadsPerBlock_Check:
    <<: *level_default
    tags: [attributes, P1]
  Unit_hipLaunchBounds_With_maxThreadsPerBlock_blocksPerCU_Check:
    <<: *level_default
    tags: [attributes, P1]
  Unit_hipDynamicShared:
    <<: *level_default
    # Below tests are failing PSDB
    disabled: [amd_windows, amd_wsl]
    tags: [memory, P0]
  Unit_hipDynamicShared2:
    <<: *level_default
    tags: [memory, P0]
  Unit_hipEmptyKernel:
    <<: *level_default
    tags: [language, smoke, P0]
  Unit_hipGridLaunch:
    <<: *level_default
    tags: [launch, smoke, P0]
  Unit_hipLanguageExtensions:
    <<: *level_default
    tags: [language, P1]
  Unit_hipLaunchParm:
    <<: *level_default
    tags: [launch, P1]
  Unit_hipLaunchParmFunctor:
    <<: *level_default
    tags: [launch, P1]
  Unit_kernel_chkConstantViaKernel:
    <<: *level_default
    tags: [memory, P0]
  Unit_kernel_chkGlobalArrAndGlobalVaribleViaKernelFn:
    <<: *level_default
    tags: [memory, P0]
  Unit_kernel_MemoryOperationsViaKernels:
    <<: *level_default
    tags: [memory, P0]
  Unit_kernel_LaunchBounds_Functional:
    <<: *level_default
    tags: [attributes, smoke, P0]
  Unit_kernel_Assign_threadIdx_to_auto:
    <<: *level_default
    tags: [language, P0]
  Unit_hipLaunchKernelExC_NegetiveTsts:
    <<: *level_default
    tags: [launch]
  Unit_hipLaunchKernelEx_NegetiveTsts:
    <<: *level_default
    tags: [launch]
  Unit_hipLaunchKernelEx_Functional:
    <<: *level_default
    tags: [launch, P0]
  Unit_hipLaunchKernelEx_With_Different_Kernels:
    <<: *level_default
    tags: [launch]
  Unit_hipLaunchKernelEx_With_CooperativeKernelWithArgs:
    <<: *level_default
    tags: [launch]
  Unit_hipLaunchKernelEx_With_MaxBlockDims:
    <<: *level_default
    tags: [launch]
  Unit_kernel_ChkPrintf:
    <<: *level_default
    tags: [language, P0]
  Unit_hipExtLaunchKernelGGL:
    <<: *level_default
    tags: [launch, P0]
  Unit_hipSetupArgument_Simple:
    <<: *level_default
    tags: [launch, P1]
  Unit_hipSetupArgument_Execute_Kernel_And_Check_Result:
    <<: *level_default
    tags: [launch, P0]
  Unit_ConfigureCall:
    <<: *level_default
    tags: [launch, P1]
  Unit_ConfigureCall_CheckParams:
    <<: *level_default
    tags: [launch, P1]
  Unit_hipGridLaunch_ExceedMaxGridDim_Negative:
    <<: *level_default
    disabled: [amd_windows, amd_linux, amd_wsl]
    tags: [launch]
  Unit_hipExtDynDataPrefetch_NegativeTests:
    <<: *level_default
    tags: [launch, P1]
  Unit_hipExtDynDataPrefetch_FunctionalDaxpy:
    <<: *level_default
    tags: [launch, P1]
  Unit_hipExtDynDataPrefetch_SingleRegion:
    <<: *level_default
    tags: [launch, P1]
  Unit_hipExtDynDataPrefetch_TemporalHints:
    <<: *level_default
    tags: [launch, P1]
  Unit_KernelStackSize:
    <<: *level_default
    tags: [P0]
    disabled: [amd_linux, amd_windows, amd_wsl]
  Unit_Validate_User_Sgpr_Count:
    <<: *level_default
  Unit_hipGridLaunch_MaxGridDim_DeviceProperties:
    <<: *level_default
    tags: [launch]
  Unit_hipGridLaunch_MaxGridDim_GetDeviceAttribute:
    <<: *level_default
    tags: [launch]
  Unit_hipLaunchParmFunctor_kernel_arg_prefetch:
    <<: *level_default
    tags: [launch]
  Unit_kernel_BlockDim3D_Validation_Functional:
    <<: *level_default
    tags: [launch]
