---
multiThread:
  Unit_hipMemsetAsync_QueueJobsMultithreaded:
    <<: *level_default
    tags: [memory, P1]
    # AIRUNTIME-2291: temporarily disabled (hangs in CI 942)
    disabled: [amd_windows, amd_wsl]
  Unit_hipMultiThreadDevice_Streams:
    <<: *level_default
    tags: [device_mgmt, P0]
  Unit_hipMultiThreadDevice_SerialPyramid:
    <<: *level_default
    # Rock_Linux_Failures_on_gfx94X
    disabled: [amd_linux, amd_wsl]
    tags: [device_mgmt, P1]
  Unit_hipMultiThreadDevice_ParallelPyramid:
    <<: *level_default
    tags: [device_mgmt, P1]
  Unit_hipMultiThreadDevice_NearZero:
    <<: *level_default
    # Note: Windows disabled
    disabled: [amd_windows, amd_wsl]
    tags: [device_mgmt, P1]
  Unit_hipMultiThreadStreams1_AsyncSync:
    <<: *level_default
    tags: [stream, P0]
  Unit_hipMultiThreadStreams1_AsyncAsync:
    <<: *level_default
    tags: [stream, P0]
  Unit_hipMultiThreadStreams1_AsyncSame:
    <<: *level_default
    tags: [stream, P0]
  Unit_hipMultiThreadStreams2:
    <<: *level_default
    tags: [stream, P0]
