---
p2p:
  Unit_hipDeviceGetP2PAttribute_Basic:
    <<: *level_default
    tags: [multigpu]
  Unit_hipDeviceGetP2PAttribute_Negative:
    <<: *level_default
    tags: [multigpu]
  Unit_hipP2pLinkTypeAndHopFunc:
    <<: *level_default
    tags: [multigpu]
