---
printf:
  Unit_Printf_flags_Sanity_Positive:
    <<: *level_default
    # Below test fails in external CI for PR https://github.com/ROCm-Developer-Tools/hip-tests/pull/274
    disabled: [amd_windows, amd_wsl]
  Unit_Printf_length_Sanity_Positive:
    <<: *level_default
    # Below test fails in external CI for PR https://github.com/ROCm-Developer-Tools/hip-tests/pull/274
    disabled: [amd_windows, amd_wsl]
  Unit_Printf_specifier_Sanity_Positive: *level_default
  Unit_Printf_Negative_Parameters_RTC: *level_default
  Unit_Buffered_Printf_Flags: *level_default
  Unit_Buffered_Printf_Specifier: *level_default
  Unit_Host_Printf: *level_default
  Unit_NonHost_Printf_basic: *level_default
  Unit_NonHost_Printf_Positive_DuplicateFormatStringMetadata: *level_default
  Unit_NonHost_Printf_loop: *level_default
  Unit_NonHost_Printf_multiple_Threads: *level_default
  Unit_NonHost_Printf_BufferAvailability: *level_default
  Unit_Printf_ManyDevicesTest:
    <<: *level_default
    tags: []
  Unit_Printf_PrintfStar: *level_default
  Unit_Printf_PrintfManyWaves: *level_default
  Unit_Printf_PrintfWidthPrecision: *level_default
  Unit_Printf_PrintfBasicTsts: *level_default
  Unit_Printf_PrintfAltFormsTsts: *level_default
  Unit_Printf_HostcallLargeStaticTls_Positive: *level_default
  Unit_Printf_HostcallUndersizedStackRequest_Positive: *level_default
