---
synchronization:
  Unit_Copy_Coherency:
    <<: *level_default
    tags: [coherency]
  Unit_cache_coherency_cpu_gpu:
    <<: *level_default
    tags: [coherency]
  Unit_cache_coherency_gpu_gpu:
    <<: *level_default
    tags: [coherency, multigpu]
