---
virtualMemoryManagement:
  Unit_hipMemGetAllocationGranularity_AllGPUs:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemGetAllocationGranularity_NegativeTests:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemGetAllocationGranularity_Capture: *level_default
  Unit_hipMemRetainAllocationHandle_SetGet:
    <<: *level_default
    disabled: [amd_wsl]
  Unit_hipMemRetainAllocationHandle_NegTst:
    <<: *level_default
    disabled: [amd_wsl]
  Unit_hipMemRetainAllocationHandle_Capture: *level_default
  Unit_hipMemImportFromShareableHandle_Positive_Basic: *level_default
  Unit_hipMemImportFromShareableHandle_Negative_Parameters: *level_default
  Unit_hipMemImportFromShareableHandle_MulProc_ChldUseHdl: *level_default
  Unit_hipMemImportFromShareableHandle_MulProc_ParntChldUseHdl: *level_default
  Unit_hipMemImportFromShareableHandle_MulProc_GrndChldUseHdl: *level_default
  Unit_hipMemImportFromShareableHandle_Capture: *level_default
  Unit_hipMemGetHandleForAddressRange_Negative: *level_default
  Unit_hipMemGetHandleForAddressRange_DeviceMemory:
    <<: *level_default
    # Does not play well with ASAN
    disabled: [asan]
  Unit_hipMemGetHandleForAddressRange_DeviceMemory_PcieFlag:
    <<: *level_default
    # Does not play well with ASAN
    disabled: [asan]
  Unit_hipMemGetHandleForAddressRange_VM: *level_default
  Unit_hipMemGetHandleForAddressRange_VM_PcieFlag: *level_default
  Unit_hipMemGetHandleForAddressRange_DeviceMemory_InAnotherDevice:
    <<: *level_default
    # Does not play well with ASAN
    disabled: [asan]
    tags: [multigpu]
  Unit_hipMemGetHandleForAddressRange_VM_InAnotherDevice:
    <<: *level_default
    tags: [multigpu]
  Unit_hipMemGetHandleForAddressRange_MulProc_Socket_DeviceMem:
    <<: *level_default
    # Does not play well with ASAN
    disabled: [asan]
  Unit_hipMemGetHandleForAddressRange_MulProc_Socket_VM:
    <<: *level_default
    # Does not play well with ASAN
    disabled: [asan]
  Unit_hipMemGetHandleForAddressRange_MultipleThreads: *level_default
  Unit_hipMemGetHandleForAddressRange_DifferentOffsets: *level_default
  Unit_hipMemGetHandleForAddressRange_NoLeakOnRelease: *level_default
  Unit_hipMemExportToShareableHandle_Positive_Basic: *level_default
  Unit_hipMemExportToShareableHandle_Negative_Parameters: *level_default
  Unit_hipMemExportToShareableHandle_Capture: *level_default
  Unit_hipGetProcAddress_VMM: *level_default
  Unit_hipMemAddressFree_negative:
    <<: *level_default
    # (amd_windows) NOTE: The following test is disabled due to defect - EXSWHTEC-244
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemAddressFree_Capture: *level_default
  Unit_hipMemAddressReserve_AlignmentTest:
    <<: *level_default
    # (amd_windows) NOTE: The following test is disabled due to defect - EXSWHTEC-245
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemAddressReserve_Negative:
    <<: *level_default
    # === Patch which removes the typetraits implementation from std namespace in hiprtc is reverted ===
    disabled: [amd_wsl]
  Unit_hipMemAddressReserve_Capture: *level_default
  Unit_hipMemCreate_BasicAllocateDeAlloc_MultGranularity:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemCreate_ChkDev2HstMemcpy_ReleaseHdlPostUnmap:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemCreate_ChkDev2HstMemcpy_ReleaseHdlPreUse:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemCreate_ChkWithKerLaunch:
    <<: *level_default
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_MapNonContiguousChunks:
    <<: *level_default
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_ChkWithMemset:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemCreate_Negative:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemCreate_Capture: *level_default
  Unit_hipMemCreate_HostNuma_Granularity:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_HostNuma_BasicAllocDealloc:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_HostNuma_ChkDev2HstMemcpy:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_HostNuma_ChkWithKerLaunch:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_HostNuma_HostAndDeviceAccess:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_HostNuma_NumaTypedAccess:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_HostNuma_Negative:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemCreate_HostNuma_ExportImport:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_SetGet:
    <<: *level_default
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_MultDevSetGet:
    <<: *level_default
    tags: [multigpu]
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_EntireVMMRangeSetGet:
    <<: *level_default
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemGetAccess_NegTst:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_FuncTstOnMultDev:
    <<: *level_default
    tags: [multigpu]
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_ChangeAccessProp:
    <<: *level_default
    # (amd_windows) SWDEV-413997: VMM test still failing in windows
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_Vmm2UnifiedMemCpy:
    <<: *level_default
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_Vmm2DevMemCpy:
    <<: *level_default
    # (amd_windows) SWDEV-444041: These tests fail randomly in gfx1030 MGU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_Vmm2PeerDevMemCpy:
    <<: *level_default
    tags: [multigpu]
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_Vmm2PeerPeerMemCpy:
    <<: *level_default
    tags: [multigpu]
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemSetAccess_Vmm2VMMMemCpy:
    <<: *level_default
    # (amd_windows) SWDEV-444041: These tests fail in gfx1100 MGPU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_Vmm2VMMInterDevMemCpy:
    <<: *level_default
    tags: [multigpu]
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_GrowVMM:
    <<: *level_default
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_Multithreaded:
    <<: *level_default
    # (amd_windows) SWDEV-444031: This test fails in gfx1101 MGPU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccess_negative:
    <<: *level_default
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetGetAccess_Capture: *level_default
  Unit_hipMemSetAccessHostDevice_hostalloc:
    <<: *level_default
    # SWDEV-555665
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemSetAccessHost_devicealloc:
    <<: *level_default
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemGetAllocationPropertiesFromHandle_functional:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemGetAllocationPropertiesFromHandle_Negative:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemGetAllocationPropertiesFromHandle_Capture: *level_default
  Unit_hipMemMap_Positive_APU_LargeAllocSpill: *level_default
  Unit_hipMemMap_SameMemoryReuse:
    <<: *level_default
    # (amd_windows) SWDEV-444041: These tests fail randomly in gfx1030 MGU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemMap_PhysicalMemoryReuse_SingleGPU:
    <<: *level_default
    # (amd_windows) SWDEV-444041: These tests fail in gfx1100 MGPU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemMap_PhysicalMemory_Map2MultVMMs:
    <<: *level_default
    # (amd_windows) SWDEV-444041: These tests fail in gfx1100 MGPU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemMap_UnmapOneAliasOfMultiAliasedHandle:
    <<: *level_default
    # (amd_windows) SWDEV-444041: These tests fail in gfx1100 MGPU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemMap_PhysicalMemoryReuse_MultiDev:
    <<: *level_default
    tags: [multigpu]
    # (amd_windows) SWDEV-444041: These tests fail in gfx1100 MGPU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemMap_VMMMemoryReuse_SingleGPU:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemMap_VMMMemoryReuse_MultiGPU:
    <<: *level_default
    tags: [multigpu]
    # (amd_windows) SWDEV-396615 mGPUs not considered correctly
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemMap_MapPartialVMMMem:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemMap_negative:
    <<: *level_default
    # (amd_windows) SWDEV-444041: These tests fail randomly in gfx1030 MGU
    # (amd_wsl) Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_windows, amd_wsl]
  Unit_hipMemMap_Capture: *level_default
  Unit_hipMemMap_Retrieve_AllocationHandle: *level_default
  Unit_hipMemMap_Retrieve_MultiAllocationHandle: *level_default
  Unit_hipMemMap_CheckAddMemObj: *level_default
  Unit_hipMemMap_RoundTrip: *level_default
  Unit_hipMemMap_ConcurrentDisjointMapsNoDeadlock: *level_default
  Unit_hipMemRelease_negative:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemRelease_Capture: *level_default
  Unit_hipMemUnmap_negative:
    <<: *level_default
    # Patch which removes the typetraits implementation from std namespace in hiprtc is reverted
    disabled: [amd_wsl]
  Unit_hipMemUnmap_Capture: *level_default
  Unit_hipMemUnmap_CrossLinksTornDown: *level_default
  Unit_hipMemUnmap_RemapCrossLinks: *level_default
  Unit_hipMemUnmap_DirectPath_BasicRoundTrip: *level_default
  Unit_hipMemUnmap_DirectPath_InFlightKernelDrained: *level_default
  Unit_hipMemMapArrayAsync_Positive_Basic:
    <<: *level_default
    tags: [image]
    # Below tests are failing PSDB
    disabled: [nvidia_linux, nvidia_windows]
  Unit_hipMemSetAccess_SegmentsAccess: *level_default
  Unit_hipMemExportFabricHandleToStdout_Positive_Basic: *level_default
