// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

//go:build linux && cgo

package amdsmi

/*
#include <stddef.h>
#include <amd_smi/amdsmi.h>
*/
import "C"

type VRAMType uint32

const (
	AMDSMI_VRAM_TYPE_UNKNOWN VRAMType = C.AMDSMI_VRAM_TYPE_UNKNOWN
	AMDSMI_VRAM_TYPE_HBM     VRAMType = C.AMDSMI_VRAM_TYPE_HBM
	AMDSMI_VRAM_TYPE_HBM2    VRAMType = C.AMDSMI_VRAM_TYPE_HBM2
	AMDSMI_VRAM_TYPE_HBM2E   VRAMType = C.AMDSMI_VRAM_TYPE_HBM2E
	AMDSMI_VRAM_TYPE_HBM3    VRAMType = C.AMDSMI_VRAM_TYPE_HBM3
	AMDSMI_VRAM_TYPE_HBM3E   VRAMType = C.AMDSMI_VRAM_TYPE_HBM3E
	AMDSMI_VRAM_TYPE_DDR2    VRAMType = C.AMDSMI_VRAM_TYPE_DDR2
	AMDSMI_VRAM_TYPE_DDR3    VRAMType = C.AMDSMI_VRAM_TYPE_DDR3
	AMDSMI_VRAM_TYPE_DDR4    VRAMType = C.AMDSMI_VRAM_TYPE_DDR4
	AMDSMI_VRAM_TYPE_DDR5    VRAMType = C.AMDSMI_VRAM_TYPE_DDR5
	AMDSMI_VRAM_TYPE_GDDR1   VRAMType = C.AMDSMI_VRAM_TYPE_GDDR1
	AMDSMI_VRAM_TYPE_GDDR2   VRAMType = C.AMDSMI_VRAM_TYPE_GDDR2
	AMDSMI_VRAM_TYPE_GDDR3   VRAMType = C.AMDSMI_VRAM_TYPE_GDDR3
	AMDSMI_VRAM_TYPE_GDDR4   VRAMType = C.AMDSMI_VRAM_TYPE_GDDR4
	AMDSMI_VRAM_TYPE_GDDR5   VRAMType = C.AMDSMI_VRAM_TYPE_GDDR5
	AMDSMI_VRAM_TYPE_GDDR6   VRAMType = C.AMDSMI_VRAM_TYPE_GDDR6
	AMDSMI_VRAM_TYPE_GDDR7   VRAMType = C.AMDSMI_VRAM_TYPE_GDDR7
	AMDSMI_VRAM_TYPE_LPDDR4  VRAMType = C.AMDSMI_VRAM_TYPE_LPDDR4
	AMDSMI_VRAM_TYPE_LPDDR5  VRAMType = C.AMDSMI_VRAM_TYPE_LPDDR5
	AMDSMI_VRAM_TYPE__MAX    VRAMType = C.AMDSMI_VRAM_TYPE__MAX
)
