// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

//go:build linux && cgo

package amdsmi

/*
#include <stddef.h>
#include <amd_smi/amdsmi.h>
// CGO reads high-bit enum constants as signed unless their expression has an unsigned type.
#define AMDSMI_GPU_BLOCK_RESERVED ((unsigned long long)AMDSMI_GPU_BLOCK_RESERVED)
*/
import "C"

type GPUBlock uint64
type RASState uint32

type ECCCounts struct {
	Correctable   uint64
	Uncorrectable uint64
	Deferred      uint64
}

// RASFeatureInfo contains populated native metadata, not an overall health assessment.
type RASFeatureInfo struct {
	EEPROMVersion       uint32
	ECCCorrectionSchema uint32
}

const (
	AMDSMI_GPU_BLOCK_INVALID    GPUBlock = C.AMDSMI_GPU_BLOCK_INVALID
	AMDSMI_GPU_BLOCK_FIRST      GPUBlock = C.AMDSMI_GPU_BLOCK_FIRST
	AMDSMI_GPU_BLOCK_UMC        GPUBlock = C.AMDSMI_GPU_BLOCK_UMC
	AMDSMI_GPU_BLOCK_SDMA       GPUBlock = C.AMDSMI_GPU_BLOCK_SDMA
	AMDSMI_GPU_BLOCK_GFX        GPUBlock = C.AMDSMI_GPU_BLOCK_GFX
	AMDSMI_GPU_BLOCK_MMHUB      GPUBlock = C.AMDSMI_GPU_BLOCK_MMHUB
	AMDSMI_GPU_BLOCK_ATHUB      GPUBlock = C.AMDSMI_GPU_BLOCK_ATHUB
	AMDSMI_GPU_BLOCK_PCIE_BIF   GPUBlock = C.AMDSMI_GPU_BLOCK_PCIE_BIF
	AMDSMI_GPU_BLOCK_HDP        GPUBlock = C.AMDSMI_GPU_BLOCK_HDP
	AMDSMI_GPU_BLOCK_XGMI_WAFL  GPUBlock = C.AMDSMI_GPU_BLOCK_XGMI_WAFL
	AMDSMI_GPU_BLOCK_DF         GPUBlock = C.AMDSMI_GPU_BLOCK_DF
	AMDSMI_GPU_BLOCK_SMN        GPUBlock = C.AMDSMI_GPU_BLOCK_SMN
	AMDSMI_GPU_BLOCK_SEM        GPUBlock = C.AMDSMI_GPU_BLOCK_SEM
	AMDSMI_GPU_BLOCK_MP0        GPUBlock = C.AMDSMI_GPU_BLOCK_MP0
	AMDSMI_GPU_BLOCK_MP1        GPUBlock = C.AMDSMI_GPU_BLOCK_MP1
	AMDSMI_GPU_BLOCK_FUSE       GPUBlock = C.AMDSMI_GPU_BLOCK_FUSE
	AMDSMI_GPU_BLOCK_MCA        GPUBlock = C.AMDSMI_GPU_BLOCK_MCA
	AMDSMI_GPU_BLOCK_VCN        GPUBlock = C.AMDSMI_GPU_BLOCK_VCN
	AMDSMI_GPU_BLOCK_JPEG       GPUBlock = C.AMDSMI_GPU_BLOCK_JPEG
	AMDSMI_GPU_BLOCK_IH         GPUBlock = C.AMDSMI_GPU_BLOCK_IH
	AMDSMI_GPU_BLOCK_MPIO       GPUBlock = C.AMDSMI_GPU_BLOCK_MPIO
	AMDSMI_GPU_BLOCK_MMSCH      GPUBlock = C.AMDSMI_GPU_BLOCK_MMSCH
	AMDSMI_GPU_BLOCK_MP5        GPUBlock = C.AMDSMI_GPU_BLOCK_MP5
	AMDSMI_GPU_BLOCK_ATU        GPUBlock = C.AMDSMI_GPU_BLOCK_ATU
	AMDSMI_GPU_BLOCK_DACC_BE    GPUBlock = C.AMDSMI_GPU_BLOCK_DACC_BE
	AMDSMI_GPU_BLOCK_ECLR       GPUBlock = C.AMDSMI_GPU_BLOCK_ECLR
	AMDSMI_GPU_BLOCK_KPX_SERDES GPUBlock = C.AMDSMI_GPU_BLOCK_KPX_SERDES
	AMDSMI_GPU_BLOCK_LSDMA      GPUBlock = C.AMDSMI_GPU_BLOCK_LSDMA
	AMDSMI_GPU_BLOCK_MPART      GPUBlock = C.AMDSMI_GPU_BLOCK_MPART
	AMDSMI_GPU_BLOCK_MPIFOE     GPUBlock = C.AMDSMI_GPU_BLOCK_MPIFOE
	AMDSMI_GPU_BLOCK_MPRAS      GPUBlock = C.AMDSMI_GPU_BLOCK_MPRAS
	AMDSMI_GPU_BLOCK_NBIF       GPUBlock = C.AMDSMI_GPU_BLOCK_NBIF
	AMDSMI_GPU_BLOCK_NBIO       GPUBlock = C.AMDSMI_GPU_BLOCK_NBIO
	AMDSMI_GPU_BLOCK_OXRP       GPUBlock = C.AMDSMI_GPU_BLOCK_OXRP
	AMDSMI_GPU_BLOCK_PCIE_PL    GPUBlock = C.AMDSMI_GPU_BLOCK_PCIE_PL
	AMDSMI_GPU_BLOCK_PCS_XGMI   GPUBlock = C.AMDSMI_GPU_BLOCK_PCS_XGMI
	AMDSMI_GPU_BLOCK_PIE        GPUBlock = C.AMDSMI_GPU_BLOCK_PIE
	AMDSMI_GPU_BLOCK_CS         GPUBlock = C.AMDSMI_GPU_BLOCK_CS
	AMDSMI_GPU_BLOCK_SHUB       GPUBlock = C.AMDSMI_GPU_BLOCK_SHUB
	AMDSMI_GPU_BLOCK_SSBDCI     GPUBlock = C.AMDSMI_GPU_BLOCK_SSBDCI
	AMDSMI_GPU_BLOCK_UCIE_PCS   GPUBlock = C.AMDSMI_GPU_BLOCK_UCIE_PCS
	AMDSMI_GPU_BLOCK_LAST       GPUBlock = C.AMDSMI_GPU_BLOCK_LAST
	AMDSMI_GPU_BLOCK_RESERVED   GPUBlock = C.AMDSMI_GPU_BLOCK_RESERVED
)

const (
	AMDSMI_RAS_ERR_STATE_NONE     RASState = C.AMDSMI_RAS_ERR_STATE_NONE
	AMDSMI_RAS_ERR_STATE_DISABLED RASState = C.AMDSMI_RAS_ERR_STATE_DISABLED
	AMDSMI_RAS_ERR_STATE_PARITY   RASState = C.AMDSMI_RAS_ERR_STATE_PARITY
	AMDSMI_RAS_ERR_STATE_SING_C   RASState = C.AMDSMI_RAS_ERR_STATE_SING_C
	AMDSMI_RAS_ERR_STATE_MULT_UC  RASState = C.AMDSMI_RAS_ERR_STATE_MULT_UC
	AMDSMI_RAS_ERR_STATE_POISON   RASState = C.AMDSMI_RAS_ERR_STATE_POISON
	AMDSMI_RAS_ERR_STATE_ENABLED  RASState = C.AMDSMI_RAS_ERR_STATE_ENABLED
	AMDSMI_RAS_ERR_STATE_LAST     RASState = C.AMDSMI_RAS_ERR_STATE_LAST
	AMDSMI_RAS_ERR_STATE_INVALID  RASState = C.AMDSMI_RAS_ERR_STATE_INVALID
)
