// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

//go:build linux && cgo

package amdsmi

/*
#include <stddef.h>
#include <amd_smi/amdsmi.h>
*/
import "C"

const (
	AMDSMI_STATUS_SUCCESS             StatusCode = C.AMDSMI_STATUS_SUCCESS
	AMDSMI_STATUS_INVAL               StatusCode = C.AMDSMI_STATUS_INVAL
	AMDSMI_STATUS_NOT_SUPPORTED       StatusCode = C.AMDSMI_STATUS_NOT_SUPPORTED
	AMDSMI_STATUS_NOT_YET_IMPLEMENTED StatusCode = C.AMDSMI_STATUS_NOT_YET_IMPLEMENTED
	AMDSMI_STATUS_FAIL_LOAD_MODULE    StatusCode = C.AMDSMI_STATUS_FAIL_LOAD_MODULE
	AMDSMI_STATUS_FAIL_LOAD_SYMBOL    StatusCode = C.AMDSMI_STATUS_FAIL_LOAD_SYMBOL
	AMDSMI_STATUS_DRM_ERROR           StatusCode = C.AMDSMI_STATUS_DRM_ERROR
	AMDSMI_STATUS_API_FAILED          StatusCode = C.AMDSMI_STATUS_API_FAILED
	AMDSMI_STATUS_TIMEOUT             StatusCode = C.AMDSMI_STATUS_TIMEOUT
	AMDSMI_STATUS_RETRY               StatusCode = C.AMDSMI_STATUS_RETRY
	AMDSMI_STATUS_NO_PERM             StatusCode = C.AMDSMI_STATUS_NO_PERM
	AMDSMI_STATUS_INTERRUPT           StatusCode = C.AMDSMI_STATUS_INTERRUPT
	AMDSMI_STATUS_IO                  StatusCode = C.AMDSMI_STATUS_IO
	AMDSMI_STATUS_ADDRESS_FAULT       StatusCode = C.AMDSMI_STATUS_ADDRESS_FAULT
	AMDSMI_STATUS_FILE_ERROR          StatusCode = C.AMDSMI_STATUS_FILE_ERROR
	AMDSMI_STATUS_OUT_OF_RESOURCES    StatusCode = C.AMDSMI_STATUS_OUT_OF_RESOURCES
	AMDSMI_STATUS_INTERNAL_EXCEPTION  StatusCode = C.AMDSMI_STATUS_INTERNAL_EXCEPTION
	AMDSMI_STATUS_INPUT_OUT_OF_BOUNDS StatusCode = C.AMDSMI_STATUS_INPUT_OUT_OF_BOUNDS
	AMDSMI_STATUS_INIT_ERROR          StatusCode = C.AMDSMI_STATUS_INIT_ERROR
	AMDSMI_STATUS_REFCOUNT_OVERFLOW   StatusCode = C.AMDSMI_STATUS_REFCOUNT_OVERFLOW
	AMDSMI_STATUS_DIRECTORY_NOT_FOUND StatusCode = C.AMDSMI_STATUS_DIRECTORY_NOT_FOUND
	AMDSMI_STATUS_IPC_ERROR           StatusCode = C.AMDSMI_STATUS_IPC_ERROR
	AMDSMI_STATUS_BUSY                StatusCode = C.AMDSMI_STATUS_BUSY
	AMDSMI_STATUS_NOT_FOUND           StatusCode = C.AMDSMI_STATUS_NOT_FOUND
	AMDSMI_STATUS_NOT_INIT            StatusCode = C.AMDSMI_STATUS_NOT_INIT
	AMDSMI_STATUS_NO_SLOT             StatusCode = C.AMDSMI_STATUS_NO_SLOT
	AMDSMI_STATUS_DRIVER_NOT_LOADED   StatusCode = C.AMDSMI_STATUS_DRIVER_NOT_LOADED
	AMDSMI_STATUS_MORE_DATA           StatusCode = C.AMDSMI_STATUS_MORE_DATA
	AMDSMI_STATUS_NO_DATA             StatusCode = C.AMDSMI_STATUS_NO_DATA
	AMDSMI_STATUS_INSUFFICIENT_SIZE   StatusCode = C.AMDSMI_STATUS_INSUFFICIENT_SIZE
	AMDSMI_STATUS_UNEXPECTED_SIZE     StatusCode = C.AMDSMI_STATUS_UNEXPECTED_SIZE
	AMDSMI_STATUS_UNEXPECTED_DATA     StatusCode = C.AMDSMI_STATUS_UNEXPECTED_DATA
	AMDSMI_STATUS_NON_AMD_CPU         StatusCode = C.AMDSMI_STATUS_NON_AMD_CPU
	AMDSMI_STATUS_NO_ENERGY_DRV       StatusCode = C.AMDSMI_STATUS_NO_ENERGY_DRV
	AMDSMI_STATUS_NO_MSR_DRV          StatusCode = C.AMDSMI_STATUS_NO_MSR_DRV
	AMDSMI_STATUS_NO_HSMP_DRV         StatusCode = C.AMDSMI_STATUS_NO_HSMP_DRV
	AMDSMI_STATUS_NO_HSMP_SUP         StatusCode = C.AMDSMI_STATUS_NO_HSMP_SUP
	AMDSMI_STATUS_NO_HSMP_MSG_SUP     StatusCode = C.AMDSMI_STATUS_NO_HSMP_MSG_SUP
	AMDSMI_STATUS_HSMP_TIMEOUT        StatusCode = C.AMDSMI_STATUS_HSMP_TIMEOUT
	AMDSMI_STATUS_NO_DRV              StatusCode = C.AMDSMI_STATUS_NO_DRV
	AMDSMI_STATUS_FILE_NOT_FOUND      StatusCode = C.AMDSMI_STATUS_FILE_NOT_FOUND
	AMDSMI_STATUS_ARG_PTR_NULL        StatusCode = C.AMDSMI_STATUS_ARG_PTR_NULL
	AMDSMI_STATUS_AMDGPU_RESTART_ERR  StatusCode = C.AMDSMI_STATUS_AMDGPU_RESTART_ERR
	AMDSMI_STATUS_SETTING_UNAVAILABLE StatusCode = C.AMDSMI_STATUS_SETTING_UNAVAILABLE
	AMDSMI_STATUS_CORRUPTED_EEPROM    StatusCode = C.AMDSMI_STATUS_CORRUPTED_EEPROM
	AMDSMI_STATUS_MAP_ERROR           StatusCode = C.AMDSMI_STATUS_MAP_ERROR
	AMDSMI_STATUS_UNKNOWN_ERROR       StatusCode = C.AMDSMI_STATUS_UNKNOWN_ERROR
)
