// Copyright Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

//go:build linux && cgo

package amdsmi

/*
#include <stddef.h>
#include <amd_smi/amdsmi.h>
*/
import "C"

type TemperatureType uint32
type TemperatureMetric uint32
type ClockType uint32
type MemoryType uint32

const maxFrequencies int = C.AMDSMI_MAX_NUM_FREQUENCIES

const (
	AMDSMI_TEMPERATURE_TYPE_EDGE                             TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_EDGE
	AMDSMI_TEMPERATURE_TYPE_FIRST                            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_FIRST
	AMDSMI_TEMPERATURE_TYPE_HOTSPOT                          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_HOTSPOT
	AMDSMI_TEMPERATURE_TYPE_JUNCTION                         TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_JUNCTION
	AMDSMI_TEMPERATURE_TYPE_VRAM                             TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_VRAM
	AMDSMI_TEMPERATURE_TYPE_HBM_0                            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_HBM_0
	AMDSMI_TEMPERATURE_TYPE_HBM_1                            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_HBM_1
	AMDSMI_TEMPERATURE_TYPE_HBM_2                            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_HBM_2
	AMDSMI_TEMPERATURE_TYPE_HBM_3                            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_HBM_3
	AMDSMI_TEMPERATURE_TYPE_PLX                              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_PLX
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_FIRST              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_FIRST
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_RETIMER_X          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_RETIMER_X
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_IBC          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_IBC
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_IBC_2        TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_IBC_2
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_VDD18_VR     TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_VDD18_VR
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_04_HBM_B_VR  TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_04_HBM_B_VR
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_04_HBM_D_VR  TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_OAM_X_04_HBM_D_VR
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_LAST               TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_NODE_LAST
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VR_FIRST                TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VR_FIRST
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD0              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD0
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD1              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD1
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD2              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD2
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD3              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_VDD3
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOC_A             TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOC_A
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOC_C             TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOC_C
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOCIO_A           TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOCIO_A
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOCIO_C           TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_SOCIO_C
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDD_085_HBM             TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDD_085_HBM
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_11_HBM_B          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_11_HBM_B
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_11_HBM_D          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_11_HBM_D
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDD_USR                 TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDD_USR
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_11_E32            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_11_E32
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_04_HBM_B          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_04_HBM_B
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_04_HBM_D          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_04_HBM_D
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_075_HBM_B         TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_075_HBM_B
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_075_HBM_D         TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_075_HBM_D
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_11_GTA_A          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_11_GTA_A
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_11_GTA_C          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_11_GTA_C
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDAN_075_GTA_A         TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDAN_075_GTA_A
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDAN_075_GTA_C         TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDAN_075_GTA_C
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_075_UCIE          TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDCR_075_UCIE
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_065_UCIEAA        TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_065_UCIEAA
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_065_UCIEAM_A      TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_065_UCIEAM_A
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_065_UCIEAM_C      TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDIO_065_UCIEAM_C
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDAN_075               TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VDDAN_075
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VR_LAST                 TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_VR_LAST
	AMDSMI_TEMPERATURE_TYPE_GPUBOARD_LAST                    TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_GPUBOARD_LAST
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_FIRST                  TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_FIRST
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FPGA               TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FPGA
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FRONT              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FRONT
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_BACK               TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_BACK
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_OAM7               TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_OAM7
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_IBC                TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_IBC
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_UFPGA              TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_UFPGA
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_OAM1               TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_OAM1
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_0_1_HSC            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_0_1_HSC
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_2_3_HSC            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_2_3_HSC
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_4_5_HSC            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_4_5_HSC
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_6_7_HSC            TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_6_7_HSC
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FPGA_0V72_VR       TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FPGA_0V72_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FPGA_3V3_VR        TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_UBB_FPGA_3V3_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_0_1_2_3_1V2_VR TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_0_1_2_3_1V2_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_4_5_6_7_1V2_VR TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_4_5_6_7_1V2_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_0_1_0V9_VR     TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_0_1_0V9_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_4_5_0V9_VR     TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_4_5_0V9_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_2_3_0V9_VR     TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_2_3_0V9_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_6_7_0V9_VR     TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_RETIMER_6_7_0V9_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_0_1_2_3_3V3_VR     TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_0_1_2_3_3V3_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_4_5_6_7_3V3_VR     TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_OAM_4_5_6_7_3V3_VR
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_IBC_HSC                TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_IBC_HSC
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_IBC                    TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_IBC
	AMDSMI_TEMPERATURE_TYPE_BASEBOARD_LAST                   TemperatureType = C.AMDSMI_TEMPERATURE_TYPE_BASEBOARD_LAST
	AMDSMI_TEMPERATURE_TYPE__MAX                             TemperatureType = C.AMDSMI_TEMPERATURE_TYPE__MAX
)

const (
	AMDSMI_TEMP_CURRENT        TemperatureMetric = C.AMDSMI_TEMP_CURRENT
	AMDSMI_TEMP_FIRST          TemperatureMetric = C.AMDSMI_TEMP_FIRST
	AMDSMI_TEMP_MAX            TemperatureMetric = C.AMDSMI_TEMP_MAX
	AMDSMI_TEMP_MIN            TemperatureMetric = C.AMDSMI_TEMP_MIN
	AMDSMI_TEMP_MAX_HYST       TemperatureMetric = C.AMDSMI_TEMP_MAX_HYST
	AMDSMI_TEMP_MIN_HYST       TemperatureMetric = C.AMDSMI_TEMP_MIN_HYST
	AMDSMI_TEMP_CRITICAL       TemperatureMetric = C.AMDSMI_TEMP_CRITICAL
	AMDSMI_TEMP_CRITICAL_HYST  TemperatureMetric = C.AMDSMI_TEMP_CRITICAL_HYST
	AMDSMI_TEMP_EMERGENCY      TemperatureMetric = C.AMDSMI_TEMP_EMERGENCY
	AMDSMI_TEMP_EMERGENCY_HYST TemperatureMetric = C.AMDSMI_TEMP_EMERGENCY_HYST
	AMDSMI_TEMP_CRIT_MIN       TemperatureMetric = C.AMDSMI_TEMP_CRIT_MIN
	AMDSMI_TEMP_CRIT_MIN_HYST  TemperatureMetric = C.AMDSMI_TEMP_CRIT_MIN_HYST
	AMDSMI_TEMP_OFFSET         TemperatureMetric = C.AMDSMI_TEMP_OFFSET
	AMDSMI_TEMP_LOWEST         TemperatureMetric = C.AMDSMI_TEMP_LOWEST
	AMDSMI_TEMP_HIGHEST        TemperatureMetric = C.AMDSMI_TEMP_HIGHEST
	AMDSMI_TEMP_SHUTDOWN       TemperatureMetric = C.AMDSMI_TEMP_SHUTDOWN
	AMDSMI_TEMP_LAST           TemperatureMetric = C.AMDSMI_TEMP_LAST
)

const (
	AMDSMI_CLK_TYPE_SYS   ClockType = C.AMDSMI_CLK_TYPE_SYS
	AMDSMI_CLK_TYPE_FIRST ClockType = C.AMDSMI_CLK_TYPE_FIRST
	AMDSMI_CLK_TYPE_GFX   ClockType = C.AMDSMI_CLK_TYPE_GFX
	AMDSMI_CLK_TYPE_DF    ClockType = C.AMDSMI_CLK_TYPE_DF
	AMDSMI_CLK_TYPE_DCEF  ClockType = C.AMDSMI_CLK_TYPE_DCEF
	AMDSMI_CLK_TYPE_SOC   ClockType = C.AMDSMI_CLK_TYPE_SOC
	AMDSMI_CLK_TYPE_MEM   ClockType = C.AMDSMI_CLK_TYPE_MEM
	AMDSMI_CLK_TYPE_PCIE  ClockType = C.AMDSMI_CLK_TYPE_PCIE
	AMDSMI_CLK_TYPE_VCLK0 ClockType = C.AMDSMI_CLK_TYPE_VCLK0
	AMDSMI_CLK_TYPE_VCLK1 ClockType = C.AMDSMI_CLK_TYPE_VCLK1
	AMDSMI_CLK_TYPE_DCLK0 ClockType = C.AMDSMI_CLK_TYPE_DCLK0
	AMDSMI_CLK_TYPE_DCLK1 ClockType = C.AMDSMI_CLK_TYPE_DCLK1
	AMDSMI_CLK_TYPE__MAX  ClockType = C.AMDSMI_CLK_TYPE__MAX
)

const (
	AMDSMI_MEM_TYPE_FIRST    MemoryType = C.AMDSMI_MEM_TYPE_FIRST
	AMDSMI_MEM_TYPE_VRAM     MemoryType = C.AMDSMI_MEM_TYPE_VRAM
	AMDSMI_MEM_TYPE_VIS_VRAM MemoryType = C.AMDSMI_MEM_TYPE_VIS_VRAM
	AMDSMI_MEM_TYPE_GTT      MemoryType = C.AMDSMI_MEM_TYPE_GTT
	AMDSMI_MEM_TYPE_LAST     MemoryType = C.AMDSMI_MEM_TYPE_LAST
)

// PowerInfo preserves native unavailable values at each field's width.
type PowerInfo struct {
	SocketPowerWatts        uint64
	CurrentSocketPowerWatts uint32
	AverageSocketPowerWatts uint32
	GFXVoltageMillivolts    uint64
	SOCVoltageMillivolts    uint64
	MemoryVoltageMillivolts uint64
	PowerLimitMicrowatts    uint32
	UBBPowerWatts           uint32
}

// PowerCapInfo may contain zero auxiliary fields after partial native success.
type PowerCapInfo struct {
	PowerCapMicrowatts        uint64
	DefaultPowerCapMicrowatts uint64
	DPMLevel                  uint64 // Level index, not MHz.
	MinPowerCapMicrowatts     uint64
	MaxPowerCapMicrowatts     uint64
}

type ClockInfo struct {
	ClockMHz     uint32
	MinClockMHz  uint32
	MaxClockMHz  uint32
	LockedRaw    uint8 // Not populated by the current bare-metal implementation.
	DeepSleepRaw uint8 // Native narrowed sleep-frequency byte.
}

type Frequencies struct {
	HasDeepSleep bool
	CurrentIndex uint32 // May be UINT32_MAX or outside Hertz.
	Hertz        []uint64
}

type Activity struct {
	GFXPercent uint32 // 65535 can indicate unavailable data.
	UMCPercent uint32
	MMPercent  uint32
}

type VRAMInfo struct {
	Type                    VRAMType
	Vendor                  string
	SizeMB                  uint64
	BitWidth                uint32
	MaxBandwidthGBPerSecond uint64
}
